import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws

const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const templates = [
  // ── 1BHK ──────────────────────────────────────────────────────────────────
  {
    id: 'template-1BHK-N-20x30-Modern',
    bhkType: '1BHK',
    style: 'Modern',
    facing: 'N',
    plotWidth: 20,
    plotHeight: 30,
    vastuScore: 72,
    tags: ['compact', 'north-facing', 'studio-style'],
    description: 'Efficient 1BHK for a 20×30ft north-facing plot. Open living-kitchen saves circulation space.',
    rooms: [
      { name: 'Foyer',        type: 'foyer',        x: 7,  y: 0,  width: 6,  height: 4,  floor: 1 },
      { name: 'Living Room',  type: 'living_room',  x: 0,  y: 4,  width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',      type: 'kitchen',      x: 12, y: 4,  width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom',      type: 'bedroom',      x: 0,  y: 14, width: 12, height: 10, floor: 1 },
      { name: 'Bathroom',     type: 'bathroom',     x: 12, y: 14, width: 8,  height: 6,  floor: 1 },
      { name: 'Store',        type: 'storage',      x: 12, y: 20, width: 8,  height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-1BHK-E-20x30-Vastu',
    bhkType: '1BHK',
    style: 'Vastu Classic',
    facing: 'E',
    plotWidth: 20,
    plotHeight: 30,
    vastuScore: 75,
    tags: ['east-facing', 'vastu-optimised', 'compact'],
    description: '1BHK on east-facing plot. Bedroom in SW, kitchen in SE — highest Vastu compliance for this size.',
    rooms: [
      { name: 'Foyer',        type: 'foyer',        x: 0,  y: 11, width: 4,  height: 8,  floor: 1 },
      { name: 'Living Room',  type: 'living_room',  x: 4,  y: 8,  width: 10, height: 12, floor: 1 },
      { name: 'Kitchen',      type: 'kitchen',      x: 14, y: 16, width: 6,  height: 10, floor: 1 },
      { name: 'Dining Room',  type: 'dining_room',  x: 4,  y: 20, width: 10, height: 6,  floor: 1 },
      { name: 'Bedroom',      type: 'bedroom',      x: 4,  y: 0,  width: 10, height: 8,  floor: 1 },
      { name: 'Bathroom',     type: 'bathroom',     x: 14, y: 0,  width: 6,  height: 8,  floor: 1 },
    ],
  },

  // ── 2BHK ──────────────────────────────────────────────────────────────────
  {
    id: 'template-2BHK-N-30x40-Modern',
    bhkType: '2BHK',
    style: 'Modern',
    facing: 'N',
    plotWidth: 30,
    plotHeight: 40,
    vastuScore: 78,
    tags: ['north-facing', 'open-plan', 'family'],
    description: 'Classic 2BHK for 30×40ft north-facing plot. Living room opens north, master bedroom in SW, kitchen SE.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',        x: 10, y: 0,  width: 10, height: 5,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',  x: 0,  y: 5,  width: 18, height: 12, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',  x: 18, y: 5,  width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',      x: 18, y: 15, width: 12, height: 10, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0, y: 17, width: 14, height: 12, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',     x: 14, y: 25, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',      x: 0,  y: 29, width: 12, height: 10, floor: 1 },
      { name: 'Bathroom',        type: 'bathroom',     x: 12, y: 31, width: 8,  height: 6,  floor: 1 },
      { name: 'Utility',         type: 'utility',      x: 20, y: 31, width: 10, height: 6,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',    x: 22, y: 25, width: 8,  height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-E-30x40-Vastu',
    bhkType: '2BHK',
    style: 'Vastu Classic',
    facing: 'E',
    plotWidth: 30,
    plotHeight: 40,
    vastuScore: 82,
    tags: ['east-facing', 'vastu-optimised', 'traditional'],
    description: 'High-scoring 2BHK on east-facing plot. Follows Vastu mandala: SE kitchen, SW master bedroom, NW children room.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 0,  y: 14, width: 5,  height: 12, floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 5,  y: 10, width: 14, height: 16, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 19, y: 10, width: 11, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 19, y: 20, width: 11, height: 12, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 5,  y: 26, width: 14, height: 14, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 19, y: 32, width: 11, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 5,  y: 0,  width: 14, height: 10, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 19, y: 0,  width: 11, height: 10, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 0,  y: 0,  width: 5,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 0,  y: 26, width: 5,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-30x50-Contemporary',
    bhkType: '2BHK',
    style: 'Contemporary',
    facing: 'N',
    plotWidth: 30,
    plotHeight: 50,
    vastuScore: 76,
    tags: ['north-facing', 'spacious', 'courtyard'],
    description: '2BHK on a generous 30×50ft plot with central courtyard for ventilation. Study nook near master.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 10, y: 0,  width: 10, height: 5,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 18, height: 14, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 18, y: 5,  width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 18, y: 15, width: 12, height: 12, floor: 1 },
      { name: 'Courtyard',       type: 'courtyard',      x: 8,  y: 19, width: 10, height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 27, width: 14, height: 14, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 14, y: 27, width: 8,  height: 8,  floor: 1 },
      { name: 'Study',           type: 'study',          x: 14, y: 35, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 41, width: 14, height: 9,  floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 14, y: 43, width: 8,  height: 7,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 22, y: 43, width: 8,  height: 7,  floor: 1 },
    ],
  },

  // ── 3BHK ──────────────────────────────────────────────────────────────────
  {
    id: 'template-3BHK-N-40x60-Modern',
    bhkType: '3BHK',
    style: 'Modern',
    facing: 'N',
    plotWidth: 40,
    plotHeight: 60,
    vastuScore: 80,
    tags: ['north-facing', 'family', 'spacious'],
    description: 'Premium 3BHK for 40×60ft north-facing plot. Double-height living, master suite in SW, 2 kids rooms on east wing.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 14, y: 0,  width: 12, height: 6,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 24, height: 16, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 24, y: 6,  width: 16, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 24, y: 18, width: 16, height: 12, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 22, width: 16, height: 14, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 16, y: 22, width: 8,  height: 8,  floor: 1 },
      { name: 'Master Wardrobe', type: 'storage',        x: 16, y: 30, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 36, width: 14, height: 12, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 14, y: 36, width: 14, height: 12, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 28, y: 36, width: 12, height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 28, y: 44, width: 12, height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 48, width: 10, height: 8,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 10, y: 48, width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-E-40x60-Vastu',
    bhkType: '3BHK',
    style: 'Vastu Classic',
    facing: 'E',
    plotWidth: 40,
    plotHeight: 60,
    vastuScore: 85,
    tags: ['east-facing', 'vastu-optimised', 'premium'],
    description: 'Best-scoring 3BHK layout. East entrance, NE Pooja room, SE kitchen, SW master — textbook Vastu compliance.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 0,  y: 22, width: 6,  height: 16, floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 6,  y: 16, width: 18, height: 20, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 24, y: 16, width: 16, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 24, y: 30, width: 16, height: 14, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 6,  y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 6,  y: 36, width: 18, height: 16, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 24, y: 44, width: 16, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 6,  y: 52, width: 16, height: 8,  floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 22, y: 52, width: 18, height: 8,  floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 0,  y: 36, width: 6,  height: 14, floor: 1 },
      { name: 'Study',           type: 'study',          x: 14, y: 0,  width: 12, height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 0,  y: 52, width: 6,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 26, y: 0,  width: 14, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-40x50-Traditional',
    bhkType: '3BHK',
    style: 'Traditional',
    facing: 'N',
    plotWidth: 40,
    plotHeight: 50,
    vastuScore: 77,
    tags: ['north-facing', 'traditional', 'courtyard'],
    description: 'Traditional 3BHK with central courtyard. Inner verandah, separate puja and storage, classic Indian layout.',
    rooms: [
      { name: 'Verandah',        type: 'foyer',          x: 10, y: 0,  width: 20, height: 6,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 20, height: 14, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 20, y: 6,  width: 20, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 20, y: 18, width: 14, height: 12, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 34, y: 18, width: 6,  height: 8,  floor: 1 },
      { name: 'Courtyard',       type: 'courtyard',      x: 12, y: 20, width: 8,  height: 10, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 20, width: 12, height: 14, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 0,  y: 34, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 8,  y: 34, width: 14, height: 12, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 22, y: 30, width: 14, height: 12, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 36, y: 30, width: 4,  height: 8,  floor: 1 },
      { name: 'Store',           type: 'storage',        x: 22, y: 42, width: 10, height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 32, y: 42, width: 8,  height: 8,  floor: 1 },
    ],
  },

  // ── 4BHK ──────────────────────────────────────────────────────────────────
  {
    id: 'template-4BHK-N-50x80-Modern',
    bhkType: '4BHK',
    style: 'Modern',
    facing: 'N',
    plotWidth: 50,
    plotHeight: 80,
    vastuScore: 81,
    tags: ['north-facing', 'luxury', 'family', 'home-office'],
    description: 'Luxury 4BHK on 50×80ft north-facing plot. Home office, double garage, master suite with walk-in wardrobe.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 18, y: 0,  width: 14, height: 6,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 28, height: 18, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 28, y: 6,  width: 22, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 28, y: 20, width: 22, height: 14, floor: 1 },
      { name: 'Home Office',     type: 'study',          x: 0,  y: 24, width: 14, height: 12, floor: 1 },
      { name: 'Guest Bedroom',   type: 'bedroom',        x: 14, y: 24, width: 14, height: 10, floor: 1 },
      { name: 'Guest Bathroom',  type: 'bathroom',       x: 28, y: 34, width: 10, height: 8,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 38, y: 34, width: 12, height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 38, y: 42, width: 12, height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 36, width: 20, height: 18, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 20, y: 42, width: 12, height: 8,  floor: 1 },
      { name: 'Walk-in Wardrobe',type: 'storage',        x: 20, y: 36, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 54, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 16, y: 54, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 32, y: 54, width: 18, height: 14, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 0,  y: 68, width: 12, height: 8,  floor: 1 },
      { name: 'Bathroom 3',      type: 'bathroom',       x: 12, y: 68, width: 12, height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 38, y: 68, width: 12, height: 10, floor: 1 },
    ],
  },

  // ── VILLA ─────────────────────────────────────────────────────────────────
  {
    id: 'template-VILLA-E-60x80-Contemporary',
    bhkType: 'VILLA',
    style: 'Contemporary',
    facing: 'E',
    plotWidth: 60,
    plotHeight: 80,
    vastuScore: 88,
    tags: ['east-facing', 'villa', 'luxury', 'courtyard', 'multi-floor'],
    description: 'Premium 5-bed villa on 60×80ft east-facing plot with open courtyard, home theatre, and terrace garden.',
    rooms: [
      // Ground floor
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 28, width: 8,  height: 24, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 8,  y: 20, width: 24, height: 28, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 32, y: 20, width: 20, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 32, y: 38, width: 20, height: 16, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 52, y: 38, width: 8,  height: 12, floor: 1 },
      { name: 'Courtyard',        type: 'courtyard',      x: 20, y: 48, width: 20, height: 20, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 8,  y: 0,  width: 10, height: 10, floor: 1 },
      { name: 'Study / Office',   type: 'study',          x: 18, y: 0,  width: 14, height: 10, floor: 1 },
      { name: 'Guest Bedroom',    type: 'bedroom',        x: 32, y: 0,  width: 18, height: 12, floor: 1 },
      { name: 'Guest Bathroom',   type: 'bathroom',       x: 50, y: 0,  width: 10, height: 12, floor: 1 },
      { name: 'Home Theatre',     type: 'living_room',    x: 0,  y: 0,  width: 8,  height: 20, floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 40, y: 54, width: 20, height: 14, floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 8,  y: 10, width: 12, height: 10, floor: 1 },
      // First floor
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 28, width: 22, height: 24, floor: 2 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 36, width: 12, height: 10, floor: 2 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 22, y: 28, width: 12, height: 8,  floor: 2 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 34, y: 28, width: 16, height: 16, floor: 2 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 34, y: 44, width: 16, height: 14, floor: 2 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 50, y: 28, width: 10, height: 16, floor: 2 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 50, y: 44, width: 10, height: 8,  floor: 2 },
      { name: 'Terrace Garden',   type: 'courtyard',      x: 0,  y: 52, width: 34, height: 18, floor: 2 },
      { name: 'Family Lounge',    type: 'living_room',    x: 0,  y: 0,  width: 20, height: 20, floor: 2 },
      { name: 'Kids Play Room',   type: 'bedroom',        x: 20, y: 0,  width: 16, height: 14, floor: 2 },
      { name: 'Staircase',        type: 'staircase',      x: 36, y: 0,  width: 14, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-VILLA-N-60x90-Traditional',
    bhkType: 'VILLA',
    style: 'Traditional',
    facing: 'N',
    plotWidth: 60,
    plotHeight: 90,
    vastuScore: 84,
    tags: ['north-facing', 'villa', 'traditional', 'joint-family'],
    description: 'Traditional north-facing villa for joint family. Separate guest wing, inner courtyard, staff quarters.',
    rooms: [
      // Ground floor
      { name: 'Entrance Verandah', type: 'foyer',          x: 18, y: 0,  width: 24, height: 6,  floor: 1 },
      { name: 'Living Room',       type: 'living_room',    x: 0,  y: 6,  width: 30, height: 18, floor: 1 },
      { name: 'Dining Room',       type: 'dining_room',    x: 30, y: 6,  width: 30, height: 14, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 30, y: 20, width: 24, height: 14, floor: 1 },
      { name: 'Pantry',            type: 'storage',        x: 54, y: 20, width: 6,  height: 8,  floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 54, y: 28, width: 6,  height: 8,  floor: 1 },
      { name: 'Pooja Room',        type: 'pooja_room',     x: 0,  y: 24, width: 10, height: 10, floor: 1 },
      { name: 'Inner Courtyard',   type: 'courtyard',      x: 18, y: 24, width: 12, height: 12, floor: 1 },
      { name: 'Guest Bedroom',     type: 'bedroom',        x: 0,  y: 34, width: 16, height: 12, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 16, y: 34, width: 10, height: 8,  floor: 1 },
      { name: 'Staff Room',        type: 'bedroom',        x: 44, y: 36, width: 16, height: 10, floor: 1 },
      { name: 'Staff Bathroom',    type: 'bathroom',       x: 44, y: 46, width: 8,  height: 6,  floor: 1 },
      { name: 'Garage',            type: 'garage',         x: 0,  y: 46, width: 20, height: 12, floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 24, y: 36, width: 12, height: 10, floor: 1 },
      // First floor
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 0,  width: 22, height: 20, floor: 2 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 22, y: 0,  width: 10, height: 10, floor: 2 },
      { name: 'Master Wardrobe',   type: 'storage',        x: 22, y: 10, width: 10, height: 10, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 32, y: 0,  width: 16, height: 14, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 32, y: 14, width: 16, height: 14, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 48, y: 0,  width: 12, height: 14, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 48, y: 14, width: 12, height: 8,  floor: 2 },
      { name: 'Family Lounge',     type: 'living_room',    x: 0,  y: 20, width: 20, height: 16, floor: 2 },
      { name: 'Study',             type: 'study',          x: 20, y: 20, width: 14, height: 12, floor: 2 },
      { name: 'Terrace',           type: 'courtyard',      x: 34, y: 22, width: 26, height: 16, floor: 2 },
      { name: 'Staircase',         type: 'staircase',      x: 0,  y: 36, width: 12, height: 10, floor: 2 },
    ],
  },
]

async function main() {
  const passwordHash = await bcrypt.hash('admin123', 12)

  await db.user.upsert({
    where: { email: 'admin@vastuplan.com' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@vastuplan.com',
      passwordHash,
      role: 'admin',
    },
  })

  console.log('✓ Admin user seeded')

  for (const t of templates) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: {
        vastuScore: t.vastuScore,
        rooms: t.rooms,
        tags: t.tags,
        description: t.description,
      },
      create: {
        id: t.id,
        bhkType: t.bhkType,
        style: t.style,
        facing: t.facing,
        plotWidth: t.plotWidth,
        plotHeight: t.plotHeight,
        plotUnit: 'ft',
        rooms: t.rooms,
        vastuScore: t.vastuScore,
        tags: t.tags,
        description: t.description ?? null,
        isPublic: true,
        useCount: 0,
      },
    })
    console.log(`  ✓ ${t.id}`)
  }

  console.log(`\nSeed complete: ${templates.length} plan templates inserted`)
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect())
