/**
 * Batch 3: 3BHK new variants (12 templates)
 */
import { PrismaClient } from '@prisma/client'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws
const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const batch3 = [
  {
    id: 'template-3BHK-S-40x60-Contemporary',
    bhkType: '3BHK', style: 'Contemporary', facing: 'S',
    plotWidth: 40, plotHeight: 60, vastuScore: 71,
    tags: ['south-facing', 'contemporary', '3bhk', 'family'],
    description: '3BHK south-facing 40×60ft. Bedrooms at north end, spacious living-dining near south entrance.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 15, y: 54, width: 10, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 40, width: 22, height: 14, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 22, y: 40, width: 18, height: 12, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 25, y: 52, width: 15, height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 26, width: 18, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 26, width: 10, height: 8,  floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 18, y: 34, width: 10, height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 12, width: 14, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 14, y: 12, width: 14, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 28, y: 12, width: 12, height: 10, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 12, floor: 1 },
      { name: 'Study',            type: 'study',          x: 28, y: 22, width: 12, height: 12, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 0,  width: 14, height: 12, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-W-40x60-Modern',
    bhkType: '3BHK', style: 'Modern', facing: 'W',
    plotWidth: 40, plotHeight: 60, vastuScore: 74,
    tags: ['west-facing', 'modern', '3bhk', 'family'],
    description: 'West-facing 3BHK on 40×60ft. Entrance west-mid, master at SW, Pooja NE, kitchen SE.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 26, width: 8,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 8,  y: 18, width: 22, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 30, y: 10, width: 10, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 30, y: 26, width: 10, height: 16, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 36, width: 18, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 18, y: 46, width: 10, height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 8,  y: 0,  width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 8,  height: 18, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 8,  y: 14, width: 10, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 28, y: 52, width: 12, height: 8,  floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 28, y: 42, width: 12, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-40x60-SouthIndian',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 40, plotHeight: 60, vastuScore: 83,
    tags: ['north-facing', 'south-indian', 'traditional', 'courtyard', 'kerala', 'vastu'],
    description: 'Kerala-style 3BHK on 40×60ft. Front verandah, central nadumuttam (courtyard), separate pooja wing.',
    rooms: [
      { name: 'Padippura/Verandah', type: 'foyer',        x: 0,  y: 0,  width: 40, height: 6,  floor: 1 },
      { name: 'Pooja Room',         type: 'pooja_room',   x: 28, y: 6,  width: 12, height: 10, floor: 1 },
      { name: 'Living Room',        type: 'living_room',  x: 0,  y: 6,  width: 28, height: 16, floor: 1 },
      { name: 'Nadumuttam',         type: 'courtyard',    x: 10, y: 22, width: 20, height: 12, floor: 1 },
      { name: 'Dining Room',        type: 'dining_room',  x: 0,  y: 22, width: 10, height: 14, floor: 1 },
      { name: 'Kitchen',            type: 'kitchen',      x: 30, y: 22, width: 10, height: 14, floor: 1 },
      { name: 'Master Bedroom',     type: 'master_bedroom', x: 0, y: 36, width: 18, height: 14, floor: 1 },
      { name: 'Master Bathroom',    type: 'bathroom',     x: 18, y: 36, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',          type: 'bedroom',      x: 0,  y: 50, width: 14, height: 10, floor: 1 },
      { name: 'Bedroom 3',          type: 'bedroom',      x: 14, y: 50, width: 14, height: 10, floor: 1 },
      { name: 'Bathroom 2',         type: 'bathroom',     x: 28, y: 50, width: 12, height: 8,  floor: 1 },
      { name: 'Store',              type: 'storage',      x: 28, y: 16, width: 12, height: 6,  floor: 1 },
      { name: 'Utility',            type: 'utility',      x: 26, y: 36, width: 14, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-E-40x50-Modern',
    bhkType: '3BHK', style: 'Modern', facing: 'E',
    plotWidth: 40, plotHeight: 50, vastuScore: 79,
    tags: ['east-facing', 'modern', '3bhk', 'master-suite'],
    description: 'Modern east-facing 3BHK on 40×50ft. Master suite at SW with walk-in, kids rooms at NW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 32, y: 21, width: 8,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 30, y: 0,  width: 10, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 10, y: 14, width: 22, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 12, width: 10, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 28, width: 10, height: 16, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 10, y: 32, width: 20, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 30, y: 32, width: 10, height: 10, floor: 1 },
      { name: 'Walk-in Wardrobe', type: 'storage',        x: 30, y: 42, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 10, y: 0,  width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 10, height: 12, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 26, y: 10, width: 14, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 44, width: 10, height: 6,  floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 10, y: 48, width: 12, height: 2,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-50x60-Modern',
    bhkType: '3BHK', style: 'Modern', facing: 'N',
    plotWidth: 50, plotHeight: 60, vastuScore: 81,
    tags: ['north-facing', 'modern', '3bhk', 'spacious', 'home-office'],
    description: 'Generous 3BHK on 50×60ft north-facing plot. Double-height living, home office, master wing at SW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 18, y: 0,  width: 14, height: 6,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 38, y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 6,  width: 30, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 30, y: 6,  width: 20, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 30, y: 20, width: 20, height: 14, floor: 1 },
      { name: 'Home Office',      type: 'study',          x: 0,  y: 24, width: 14, height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 36, width: 20, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 20, y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 20, y: 46, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 52, width: 16, height: 8,  floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 52, width: 16, height: 8,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 32, y: 52, width: 10, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 42, y: 52, width: 8,  height: 8,  floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 30, y: 36, width: 12, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-40x60-NorthIndian',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 40, plotHeight: 60, vastuScore: 78,
    tags: ['north-facing', 'north-indian', 'traditional', 'haveli', 'rajasthan'],
    description: 'North Indian Haveli-inspired 3BHK. Large central chowk (courtyard), jharokha-style verandah, separate zenana wing.',
    rooms: [
      { name: 'Dalan/Verandah',   type: 'foyer',          x: 0,  y: 0,  width: 40, height: 6,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 6,  width: 12, height: 10, floor: 1 },
      { name: 'Baithak (Living)', type: 'living_room',    x: 0,  y: 6,  width: 28, height: 14, floor: 1 },
      { name: 'Chowk (Courtyard)',type: 'courtyard',      x: 10, y: 20, width: 20, height: 14, floor: 1 },
      { name: 'Bhojankaksha (Dining)', type: 'dining_room', x: 0, y: 20, width: 10, height: 16, floor: 1 },
      { name: 'Rasoi (Kitchen)',  type: 'kitchen',        x: 30, y: 20, width: 10, height: 14, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 36, width: 16, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 16, y: 36, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 50, width: 14, height: 10, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 14, y: 50, width: 14, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 28, y: 50, width: 12, height: 10, floor: 1 },
      { name: 'Store',            type: 'storage',        x: 24, y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 34, y: 36, width: 6,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-W-40x60-Traditional',
    bhkType: '3BHK', style: 'Traditional', facing: 'W',
    plotWidth: 40, plotHeight: 60, vastuScore: 73,
    tags: ['west-facing', 'traditional', '3bhk', 'vastu'],
    description: 'West-facing traditional 3BHK on 40×60ft. Offset west entrance per Vastu, inner courtyard, zenana zone.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 24, width: 8,  height: 12, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 8,  y: 16, width: 20, height: 18, floor: 1 },
      { name: 'Inner Courtyard',  type: 'courtyard',      x: 8,  y: 34, width: 16, height: 12, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 28, y: 10, width: 12, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 28, y: 26, width: 12, height: 14, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 36, width: 18, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 0,  width: 14, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 14, y: 0,  width: 14, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 52, width: 10, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 28, y: 52, width: 12, height: 8,  floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 10, y: 52, width: 12, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-40x60-Minimalist',
    bhkType: '3BHK', style: 'Minimalist', facing: 'N',
    plotWidth: 40, plotHeight: 60, vastuScore: 76,
    tags: ['north-facing', 'minimalist', 'modern', '3bhk', 'open-plan', 'scandinavian'],
    description: 'Scandinavian-minimalist 3BHK. Open kitchen-dining-living, private sleeping wing, neutral palette.',
    rooms: [
      { name: 'Entry Hall',       type: 'foyer',          x: 14, y: 0,  width: 12, height: 5,  floor: 1 },
      { name: 'Open Living',      type: 'living_room',    x: 0,  y: 5,  width: 40, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 26, y: 23, width: 14, height: 14, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 23, width: 18, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 23, width: 8,  height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 39, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 39, width: 14, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 30, y: 39, width: 10, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 26, y: 37, width: 14, height: 2,  floor: 1 },
      { name: 'Storage',          type: 'storage',        x: 18, y: 33, width: 8,  height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-E-50x60-Vastu',
    bhkType: '3BHK', style: 'Vastu Classic', facing: 'E',
    plotWidth: 50, plotHeight: 60, vastuScore: 86,
    tags: ['east-facing', 'vastu-optimised', '3bhk', 'premium', 'spacious'],
    description: 'Premium Vastu-optimised 3BHK on 50×60ft east-facing. Perfect compass placement: NE Pooja, SE Kitchen, SW Master.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 42, y: 26, width: 8,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 38, y: 0,  width: 12, height: 12, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 14, y: 18, width: 28, height: 20, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 14, width: 14, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 32, width: 14, height: 20, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 14, y: 38, width: 24, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 38, y: 38, width: 12, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 38, y: 48, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 14, y: 0,  width: 20, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 14, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 34, y: 12, width: 16, height: 10, floor: 1 },
      { name: 'Study',            type: 'study',          x: 0,  y: 52, width: 14, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 14, y: 56, width: 12, height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-S-40x80-Modern',
    bhkType: '3BHK', style: 'Modern', facing: 'S',
    plotWidth: 40, plotHeight: 80, vastuScore: 72,
    tags: ['south-facing', 'modern', '3bhk', 'long-plot', 'family'],
    description: '3BHK on generous south-facing 40×80ft plot. Bedrooms at north, entertainment zone at south end.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 15, y: 74, width: 10, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 58, width: 24, height: 16, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 24, y: 58, width: 16, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 24, y: 72, width: 16, height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 40, width: 18, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 40, width: 10, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 18, y: 50, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 22, width: 16, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 22, width: 16, height: 18, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 32, y: 22, width: 8,  height: 14, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 14, floor: 1 },
      { name: 'Study',            type: 'study',          x: 14, y: 0,  width: 14, height: 14, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 0,  width: 14, height: 14, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-40x70-Contemporary',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 40, plotHeight: 70, vastuScore: 80,
    tags: ['north-facing', 'contemporary', '3bhk', 'long-plot', 'courtyard'],
    description: 'Contemporary 3BHK on 40×70ft long plot. Central skylit courtyard, master suite with terrace, study alcove.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 14, y: 0,  width: 12, height: 6,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 6,  width: 26, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 26, y: 6,  width: 14, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 26, y: 20, width: 14, height: 14, floor: 1 },
      { name: 'Courtyard',        type: 'courtyard',      x: 10, y: 24, width: 16, height: 10, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 34, width: 18, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 34, width: 10, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 18, y: 44, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 52, width: 16, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 52, width: 14, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 30, y: 52, width: 10, height: 12, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 28, y: 34, width: 12, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-E-40x60-SouthIndian',
    bhkType: '3BHK', style: 'Traditional', facing: 'E',
    plotWidth: 40, plotHeight: 60, vastuScore: 84,
    tags: ['east-facing', 'south-indian', 'traditional', 'courtyard', 'vastu', 'karnataka'],
    description: 'Karnataka-style east-facing 3BHK. Nalukettu-inspired with central courtyard, separate pooja room, rear utility.',
    rooms: [
      { name: 'Verandah',         type: 'foyer',          x: 32, y: 22, width: 8,  height: 16, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 30, y: 0,  width: 10, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 10, y: 14, width: 22, height: 20, floor: 1 },
      { name: 'Central Courtyard',type: 'courtyard',      x: 10, y: 34, width: 22, height: 14, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 12, width: 10, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 28, width: 10, height: 18, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 10, y: 48, width: 20, height: 12, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 30, y: 48, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 10, y: 0,  width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 10, height: 12, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 46, width: 10, height: 10, floor: 1 },
      { name: 'Store',            type: 'storage',        x: 32, y: 38, width: 8,  height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 30, y: 56, width: 10, height: 4,  floor: 1 },
    ],
  },
]

async function main() {
  console.log(`Seeding batch 3: ${batch3.length} templates…`)
  for (const t of batch3) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: { vastuScore: t.vastuScore, rooms: t.rooms, tags: t.tags, description: t.description },
      create: { ...t, plotUnit: 'ft', isPublic: true, useCount: 0 },
    })
    console.log(`  ✓ ${t.id}`)
  }
  console.log(`\nBatch 3 complete: ${batch3.length} templates`)
}

main().catch(console.error).finally(() => db.$disconnect())
