/**
 * Batch 6: 5BHK (3) + Regional Heritage (3) + Apartments (3) + Western Heritage (3) + Special (3) + Diagonal Facing (3) = 18 templates
 */
import { PrismaClient } from '@prisma/client'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws
const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const batch6 = [
  // ── 5BHK ─────────────────────────────────────────────────────────────────
  {
    id: 'template-5BHK-N-60x80-Modern',
    bhkType: '4BHK', style: 'Modern', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 82,
    tags: ['north-facing', '5-bedroom', 'modern', 'large-plot', 'home-office'],
    description: '5BHK modern home on 60×80ft. Pooja NE, kitchen SE, master SW. Includes home office and utility zone.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 20, y: 0,  width: 20, height: 6,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 26, height: 20, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 26, y: 6,  width: 14, height: 14, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 43, y: 6,  width: 14, height: 10, floor: 1 },
      { name: 'Home Office',     type: 'study',          x: 26, y: 20, width: 17, height: 6,  floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 0,  y: 26, width: 22, height: 20, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 22, y: 26, width: 18, height: 20, floor: 1 },
      { name: 'Bedroom 5',       type: 'bedroom',        x: 40, y: 26, width: 17, height: 20, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 0,  y: 46, width: 22, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 22, y: 46, width: 18, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 42, y: 50, width: 15, height: 14, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 54, width: 22, height: 22, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 22, y: 58, width: 12, height: 8,  floor: 1 },
      { name: 'Utility Room',    type: 'utility',        x: 42, y: 64, width: 15, height: 12, floor: 1 },
    ],
  },
  {
    id: 'template-5BHK-N-70x90-Luxury',
    bhkType: 'VILLA', style: 'Luxury', facing: 'N',
    plotWidth: 70, plotHeight: 90, vastuScore: 85,
    tags: ['north-facing', '5-bedroom', 'luxury', 'pool-area', 'home-theatre'],
    description: '5BHK luxury villa on 70×90ft. Two courtyards, home theatre, spa bathroom, pool deck in rear.',
    rooms: [
      { name: 'Grand Foyer',     type: 'foyer',          x: 25, y: 0,  width: 20, height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 8,  width: 30, height: 22, floor: 1 },
      { name: 'Formal Dining',   type: 'dining_room',    x: 30, y: 8,  width: 20, height: 16, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 52, y: 8,  width: 15, height: 12, floor: 1 },
      { name: 'Family Lounge',   type: 'living_room',    x: 0,  y: 30, width: 25, height: 20, floor: 1 },
      { name: 'Home Theatre',    type: 'study',          x: 25, y: 30, width: 25, height: 20, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 50, y: 55, width: 17, height: 18, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 0,  y: 50, width: 22, height: 18, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 22, y: 50, width: 22, height: 18, floor: 1 },
      { name: 'Bedroom 5',       type: 'bedroom',        x: 44, y: 30, width: 23, height: 20, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 68, width: 28, height: 18, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 28, y: 72, width: 14, height: 14, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 42, y: 68, width: 25, height: 18, floor: 1 },
      { name: 'Pool Deck',       type: 'courtyard',      x: 28, y: 68, width: 14, height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-5BHK-E-65x85-Vastu',
    bhkType: 'VILLA', style: 'Vastu Classic', facing: 'E',
    plotWidth: 65, plotHeight: 85, vastuScore: 88,
    tags: ['east-facing', '5-bedroom', 'vastu', 'joint-family', 'large-plot'],
    description: '5BHK east-facing Vastu villa on 65×85ft. Ideal for joint families. Pooja NE, kitchen SE, master SW.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 58, y: 34, width: 7,  height: 16, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 48, y: 5,  width: 14, height: 10, floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 30, y: 5,  width: 18, height: 25, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 30, y: 30, width: 25, height: 18, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 40, y: 60, width: 20, height: 18, floor: 1 },
      { name: 'Utility Room',    type: 'utility',        x: 40, y: 78, width: 20, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 62, width: 25, height: 20, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 25, y: 68, width: 13, height: 14, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 42, width: 25, height: 18, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 0,  y: 22, width: 25, height: 18, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 0,  y: 5,  width: 25, height: 16, floor: 1 },
      { name: 'Bedroom 5',       type: 'bedroom',        x: 48, y: 15, width: 14, height: 20, floor: 1 },
      { name: 'Study Room',      type: 'study',          x: 25, y: 48, width: 15, height: 12, floor: 1 },
    ],
  },

  // ── REGIONAL HERITAGE ────────────────────────────────────────────────────
  {
    id: 'template-CHETTINAD-N-60x80-Heritage',
    bhkType: '4BHK', style: 'Traditional', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 90,
    tags: ['north-facing', 'chettinad', 'heritage', 'courtyard', 'pillared-hall', 'tamil-style'],
    description: 'Tamil Nadu Chettinad mansion on 60×80ft. Grand thinnai (outer hall), pillared nethiram, central muttram courtyard.',
    rooms: [
      { name: 'Thinnai (Outer Hall)', type: 'living_room', x: 5,  y: 0,  width: 50, height: 10, floor: 1 },
      { name: 'Nethiram (Entrance Hall)', type: 'foyer',   x: 15, y: 10, width: 30, height: 8,  floor: 1 },
      { name: 'Muttram (Inner Courtyard)', type: 'courtyard', x: 18, y: 30, width: 24, height: 20, floor: 1 },
      { name: 'Pooja Room',          type: 'pooja_room',  x: 42, y: 10, width: 15, height: 12, floor: 1 },
      { name: 'Kitchen',             type: 'kitchen',     x: 42, y: 55, width: 15, height: 18, floor: 1 },
      { name: 'Dining Room',         type: 'dining_room', x: 5,  y: 55, width: 22, height: 15, floor: 1 },
      { name: 'Master Bedroom',      type: 'master_bedroom', x: 5, y: 55, width: 22, height: 18, floor: 1 },
      { name: 'Bedroom 2',           type: 'bedroom',     x: 0,  y: 20, width: 18, height: 30, floor: 1 },
      { name: 'Bedroom 3',           type: 'bedroom',     x: 42, y: 22, width: 15, height: 28, floor: 1 },
      { name: 'Bedroom 4',           type: 'bedroom',     x: 5,  y: 18, width: 13, height: 14, floor: 1 },
      { name: 'Store Room',          type: 'storage',     x: 27, y: 73, width: 30, height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-BENGALI-N-50x70-Bungalow',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 50, plotHeight: 70, vastuScore: 80,
    tags: ['north-facing', 'bengali', 'bungalow', 'verandah', 'colonial', 'heritage'],
    description: 'Bengali colonial bungalow 50×70ft. Wide north verandah, central living, detached kitchen tradition.',
    rooms: [
      { name: 'North Verandah',  type: 'courtyard',      x: 0,  y: 0,  width: 50, height: 10, floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 5,  y: 10, width: 20, height: 18, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 25, y: 10, width: 20, height: 14, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 38, y: 10, width: 10, height: 8,  floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 30, y: 50, width: 18, height: 16, floor: 1 },
      { name: 'Pantry',          type: 'storage',        x: 30, y: 44, width: 12, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 50, width: 22, height: 18, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 28, width: 22, height: 20, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 22, y: 28, width: 22, height: 20, floor: 1 },
      { name: 'Bathroom 1',      type: 'bathroom',       x: 22, y: 50, width: 8,  height: 10, floor: 1 },
      { name: 'East Verandah',   type: 'courtyard',      x: 44, y: 28, width: 6,  height: 38, floor: 1 },
    ],
  },
  {
    id: 'template-GUJARATI-N-50x65-Haveli',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 50, plotHeight: 65, vastuScore: 84,
    tags: ['north-facing', 'gujarati', 'haveli', 'chowk', 'heritage', 'ornate'],
    description: 'Gujarati haveli on 50×65ft. Ornate entrance, central chowk courtyard, elevated otla platform at front.',
    rooms: [
      { name: 'Otla (Entrance Platform)', type: 'foyer', x: 10, y: 0,  width: 30, height: 6,  floor: 1 },
      { name: 'Osri (Outer Hall)',  type: 'living_room', x: 5,  y: 6,  width: 40, height: 12, floor: 1 },
      { name: 'Chowk (Courtyard)', type: 'courtyard',   x: 15, y: 25, width: 20, height: 16, floor: 1 },
      { name: 'Pooja Room',        type: 'pooja_room',  x: 35, y: 6,  width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',     x: 32, y: 48, width: 16, height: 14, floor: 1 },
      { name: 'Dining Room',       type: 'dining_room', x: 5,  y: 44, width: 24, height: 14, floor: 1 },
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0, y: 44, width: 5, height: 18, floor: 1 },
      { name: 'Bedroom 2',         type: 'bedroom',     x: 0,  y: 18, width: 15, height: 24, floor: 1 },
      { name: 'Bedroom 3',         type: 'bedroom',     x: 35, y: 18, width: 15, height: 24, floor: 1 },
      { name: 'Store Room',        type: 'storage',     x: 5,  y: 58, width: 40, height: 6,  floor: 1 },
    ],
  },

  // ── APARTMENT LAYOUTS ───────────────────────────────────────────────────
  {
    id: 'template-1BHK-N-15x25-Apartment',
    bhkType: '1BHK', style: 'Modern', facing: 'N',
    plotWidth: 15, plotHeight: 25, vastuScore: 72,
    tags: ['north-facing', 'apartment', 'urban', 'compact', '1bhk', 'city-living'],
    description: 'Efficient 1BHK apartment on 15×25ft footprint. Open kitchen-living, Juliet balcony facing north.',
    rooms: [
      { name: 'Entrance',        type: 'foyer',          x: 4,  y: 0,  width: 7,  height: 4,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 4,  width: 10, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 10, y: 8,  width: 5,  height: 8,  floor: 1 },
      { name: 'Dining Area',     type: 'dining_room',    x: 10, y: 4,  width: 5,  height: 4,  floor: 1 },
      { name: 'Bedroom',         type: 'master_bedroom', x: 0,  y: 16, width: 10, height: 8,  floor: 1 },
      { name: 'Bathroom',        type: 'bathroom',       x: 10, y: 16, width: 5,  height: 6,  floor: 1 },
      { name: 'Balcony',         type: 'courtyard',      x: 0,  y: 0,  width: 4,  height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-22x38-Apartment',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 22, plotHeight: 38, vastuScore: 74,
    tags: ['north-facing', 'apartment', 'urban', '2bhk', 'open-plan', 'balcony'],
    description: '2BHK urban apartment on 22×38ft. Open plan living-dining, master with attached bath, north balcony.',
    rooms: [
      { name: 'Entrance',        type: 'foyer',          x: 6,  y: 0,  width: 10, height: 4,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 4,  width: 14, height: 14, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 14, y: 4,  width: 8,  height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 14, y: 14, width: 8,  height: 10, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 14, y: 24, width: 8,  height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 22, width: 14, height: 12, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 0,  y: 18, width: 8,  height: 4,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 30, width: 14, height: 8,  floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',       x: 14, y: 30, width: 8,  height: 6,  floor: 1 },
      { name: 'North Balcony',   type: 'courtyard',      x: 0,  y: 0,  width: 6,  height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-N-28x45-Apartment',
    bhkType: '3BHK', style: 'Modern', facing: 'N',
    plotWidth: 28, plotHeight: 45, vastuScore: 76,
    tags: ['north-facing', 'apartment', 'urban', '3bhk', 'high-rise', 'open-plan'],
    description: '3BHK high-rise apartment on 28×45ft. Foyer, open living-dining, 2 attached baths, study nook, large balcony.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 8,  y: 0,  width: 12, height: 5,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 18, height: 16, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 18, y: 5,  width: 10, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 18, y: 15, width: 10, height: 12, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 18, y: 27, width: 10, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 30, width: 16, height: 12, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 0,  y: 21, width: 8,  height: 9,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 21, width: 8,  height: 9,  floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 16, y: 33, width: 12, height: 10, floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',       x: 8,  y: 21, width: 10, height: 8,  floor: 1 },
      { name: 'Study Nook',      type: 'study',          x: 16, y: 27, width: 12, height: 6,  floor: 1 },
      { name: 'Balcony',         type: 'courtyard',      x: 0,  y: 0,  width: 8,  height: 5,  floor: 1 },
    ],
  },

  // ── WESTERN HERITAGE ─────────────────────────────────────────────────────
  {
    id: 'template-TUDOR-N-60x75-Heritage',
    bhkType: '4BHK', style: 'Heritage', facing: 'N',
    plotWidth: 60, plotHeight: 75, vastuScore: 68,
    tags: ['north-facing', 'tudor', 'heritage', 'western', 'half-timber', 'formal-rooms'],
    description: 'Tudor-style home on 60×75ft. Formal parlour, inglenook fireplace hall, prominent chimney stack, asymmetric gabled entry.',
    rooms: [
      { name: 'Entry Porch',     type: 'foyer',          x: 22, y: 0,  width: 16, height: 6,  floor: 1 },
      { name: 'Great Hall',      type: 'living_room',    x: 5,  y: 6,  width: 25, height: 22, floor: 1 },
      { name: 'Formal Parlour',  type: 'living_room',    x: 30, y: 6,  width: 20, height: 14, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 30, y: 20, width: 20, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 40, y: 50, width: 18, height: 18, floor: 1 },
      { name: 'Pantry',          type: 'storage',        x: 40, y: 44, width: 18, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 5,  y: 52, width: 22, height: 18, floor: 1 },
      { name: 'Master Bath',     type: 'bathroom',       x: 5,  y: 44, width: 14, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 27, y: 34, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 5,  y: 34, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 27, y: 52, width: 13, height: 18, floor: 1 },
      { name: 'Library',         type: 'study',          x: 5,  y: 28, width: 25, height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-ARTDECO-N-55x70-Modern',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 55, plotHeight: 70, vastuScore: 70,
    tags: ['north-facing', 'art-deco', 'heritage', 'western', 'geometric', 'bold-lines'],
    description: 'Art Deco inspired home on 55×70ft. Bold geometric facade, curved sunroom, symmetrical layout, stepped parapet details.',
    rooms: [
      { name: 'Sunroom Entry',   type: 'foyer',          x: 18, y: 0,  width: 19, height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 5,  y: 8,  width: 22, height: 20, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 27, y: 8,  width: 18, height: 14, floor: 1 },
      { name: 'Study',           type: 'study',          x: 27, y: 22, width: 18, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 35, y: 48, width: 18, height: 18, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 5,  y: 50, width: 22, height: 18, floor: 1 },
      { name: 'Master Bath',     type: 'bathroom',       x: 5,  y: 44, width: 12, height: 6,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 5,  y: 34, width: 22, height: 18, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 27, y: 34, width: 22, height: 18, floor: 1 },
      { name: 'Powder Room',     type: 'bathroom',       x: 45, y: 8,  width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-BARNDOMINIUM-N-60x80-Western',
    bhkType: '3BHK', style: 'Farmhouse', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 65,
    tags: ['north-facing', 'barndominium', 'farmhouse', 'western', 'open-plan', 'metal-roof'],
    description: 'Barndominium on 60×80ft. Open-plan great room with exposed trusses, wrap-around porch, large garage/workshop.',
    rooms: [
      { name: 'Wrap-Around Porch', type: 'courtyard',   x: 0,  y: 0,  width: 60, height: 8,  floor: 1 },
      { name: 'Great Room',       type: 'living_room',  x: 8,  y: 8,  width: 30, height: 28, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',      x: 38, y: 8,  width: 20, height: 18, floor: 1 },
      { name: 'Dining Area',      type: 'dining_room',  x: 38, y: 26, width: 20, height: 10, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 5, y: 50, width: 24, height: 22, floor: 1 },
      { name: 'Master Bath',      type: 'bathroom',     x: 5,  y: 44, width: 14, height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',      x: 29, y: 50, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',      x: 5,  y: 36, width: 24, height: 14, floor: 1 },
      { name: 'Garage/Workshop',  type: 'garage',       x: 38, y: 40, width: 20, height: 30, floor: 1 },
      { name: 'Laundry Room',     type: 'utility',      x: 29, y: 36, width: 9,  height: 12, floor: 1 },
    ],
  },

  // ── SPECIAL / INNOVATIVE ─────────────────────────────────────────────────
  {
    id: 'template-ACCESSIBLE-N-40x50-SeniorLiving',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 40, plotHeight: 50, vastuScore: 78,
    tags: ['north-facing', 'accessible', 'senior-living', 'single-floor', 'wide-corridors', 'vastu'],
    description: 'Accessible senior-friendly home on 40×50ft. Wide corridors 4ft+, roll-in bathroom, no level changes, ramp entry.',
    rooms: [
      { name: 'Ramp Entry',      type: 'foyer',          x: 13, y: 0,  width: 14, height: 6,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 22, height: 18, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 28, y: 6,  width: 10, height: 8,  floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 22, y: 6,  width: 18, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 26, y: 32, width: 12, height: 14, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 32, width: 20, height: 16, floor: 1 },
      { name: 'Roll-In Bathroom',type: 'bathroom',       x: 20, y: 32, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 24, width: 22, height: 8,  floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',       x: 22, y: 18, width: 10, height: 8,  floor: 1 },
      { name: 'Caregiver Room',  type: 'bedroom',        x: 30, y: 40, width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-TROPICAL-N-50x65-Courtyard',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 50, plotHeight: 65, vastuScore: 80,
    tags: ['north-facing', 'tropical', 'courtyard', 'passive-cooling', 'open-to-sky', 'rain-harvest'],
    description: 'Tropical courtyard home on 50×65ft. Central open-to-sky atrium drives cross-ventilation. Overhanging eaves and rain harvesting.',
    rooms: [
      { name: 'Entry Verandah',  type: 'courtyard',      x: 8,  y: 0,  width: 34, height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 8,  width: 20, height: 20, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 20, y: 8,  width: 16, height: 12, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 36, y: 8,  width: 12, height: 10, floor: 1 },
      { name: 'Sky Atrium',      type: 'courtyard',      x: 16, y: 24, width: 18, height: 18, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 34, y: 18, width: 14, height: 18, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 34, y: 36, width: 14, height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 44, width: 22, height: 18, floor: 1 },
      { name: 'Master Bath',     type: 'bathroom',       x: 0,  y: 36, width: 16, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 22, y: 44, width: 20, height: 18, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 0,  y: 28, width: 16, height: 16, floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',       x: 42, y: 44, width: 8,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-VASTU-PERFECT-N-40x55-Classic',
    bhkType: '3BHK', style: 'Vastu Classic', facing: 'N',
    plotWidth: 40, plotHeight: 55, vastuScore: 94,
    tags: ['north-facing', 'vastu', 'perfect-vastu', 'classic', 'high-score', 'compass-aligned'],
    description: 'Near-perfect Vastu 3BHK on 40×55ft. Pooja NE (score 100), kitchen SE (100), master SW (100), living NW (90).',
    rooms: [
      { name: 'North Entrance',  type: 'foyer',          x: 14, y: 0,  width: 12, height: 5,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 28, y: 0,  width: 10, height: 10, floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 18, height: 18, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 18, y: 5,  width: 14, height: 12, floor: 1 },
      { name: 'Brahmasthana',    type: 'courtyard',      x: 14, y: 20, width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 28, y: 35, width: 10, height: 14, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 28, y: 49, width: 10, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 38, width: 18, height: 16, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 18, y: 43, width: 10, height: 11, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 23, width: 14, height: 15, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 18, y: 17, width: 20, height: 16, floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',       x: 14, y: 23, width: 8,  height: 12, floor: 1 },
    ],
  },

  // ── DIAGONAL FACING ──────────────────────────────────────────────────────
  {
    id: 'template-2BHK-NE-30x40-Vastu',
    bhkType: '2BHK', style: 'Vastu Classic', facing: 'NE',
    plotWidth: 30, plotHeight: 40, vastuScore: 79,
    tags: ['northeast-facing', 'vastu', '2bhk', 'corner-plot', 'diagonal-facing'],
    description: '2BHK NE corner-facing plot 30×40ft. Entrance at NE corner (highly auspicious in Vastu). Pooja at NE, kitchen SE.',
    rooms: [
      { name: 'NE Corner Entrance', type: 'foyer',      x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',   x: 0,  y: 0,  width: 22, height: 18, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',    x: 22, y: 8,  width: 8,  height: 8,  floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',   x: 0,  y: 18, width: 15, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',       x: 20, y: 24, width: 10, height: 12, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom',x: 0,  y: 28, width: 18, height: 12, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',      x: 18, y: 28, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',       x: 0,  y: 16, width: 15, height: 12, floor: 1 },
      { name: 'Utility',         type: 'utility',       x: 20, y: 36, width: 10, height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-NW-40x55-Modern',
    bhkType: '3BHK', style: 'Modern', facing: 'NW',
    plotWidth: 40, plotHeight: 55, vastuScore: 74,
    tags: ['northwest-facing', 'modern', '3bhk', 'corner-plot', 'diagonal-facing'],
    description: '3BHK NW-facing corner plot 40×55ft. Garage at NW entry. Pooja NE, kitchen SE, master SW for Vastu.',
    rooms: [
      { name: 'NW Entry/Garage', type: 'garage',        x: 0,  y: 0,  width: 14, height: 12, floor: 1 },
      { name: 'Foyer',           type: 'foyer',         x: 14, y: 0,  width: 12, height: 6,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',    x: 30, y: 0,  width: 10, height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',   x: 0,  y: 12, width: 22, height: 18, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',   x: 22, y: 6,  width: 18, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',       x: 28, y: 35, width: 12, height: 14, floor: 1 },
      { name: 'Utility',         type: 'utility',       x: 28, y: 49, width: 12, height: 6,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom',x: 0,  y: 38, width: 20, height: 17, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',      x: 20, y: 43, width: 8,  height: 10, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',       x: 0,  y: 30, width: 20, height: 8,  floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',       x: 20, y: 20, width: 18, height: 18, floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',      x: 0,  y: 22, width: 10, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-3BHK-SE-45x55-Contemporary',
    bhkType: '3BHK', style: 'Contemporary', facing: 'SE',
    plotWidth: 45, plotHeight: 55, vastuScore: 72,
    tags: ['southeast-facing', 'contemporary', '3bhk', 'corner-plot', 'diagonal-facing'],
    description: '3BHK SE-facing corner plot 45×55ft. Road on east+south sides. Kitchen near SE entry (Vastu SE=Agni), living NW.',
    rooms: [
      { name: 'SE Entry Foyer',  type: 'foyer',         x: 36, y: 44, width: 9,  height: 11, floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',    x: 34, y: 0,  width: 10, height: 10, floor: 1 },
      { name: 'Living Room',     type: 'living_room',   x: 0,  y: 0,  width: 22, height: 22, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',   x: 22, y: 0,  width: 16, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',       x: 30, y: 38, width: 14, height: 14, floor: 1 },
      { name: 'Utility',         type: 'utility',       x: 30, y: 30, width: 14, height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom',x: 0,  y: 36, width: 22, height: 18, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',      x: 22, y: 42, width: 8,  height: 12, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',       x: 0,  y: 22, width: 20, height: 14, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',       x: 20, y: 14, width: 20, height: 16, floor: 1 },
      { name: 'Common Bathroom', type: 'bathroom',      x: 22, y: 30, width: 8,  height: 12, floor: 1 },
    ],
  },
]

async function main() {
  console.log(`Seeding batch 6: ${batch6.length} templates…`)
  for (const t of batch6) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: { ...t },
      create: { ...t },
    })
    console.log(`  ✓ ${t.id}`)
  }
  console.log(`\nBatch 6 complete: ${batch6.length} templates`)
}

main().catch(console.error).finally(() => db.$disconnect())
