/**
 * Batch 2: 2BHK new variants (13 templates)
 */
import { PrismaClient } from '@prisma/client'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws
const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const batch2 = [
  {
    id: 'template-2BHK-S-30x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'S',
    plotWidth: 30, plotHeight: 40, vastuScore: 68,
    tags: ['south-facing', 'modern', '2bhk'],
    description: '2BHK south-facing 30×40ft. Entrance south-center, bedrooms at north, kitchen SE, Pooja NE.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 10, y: 34, width: 10, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 22, width: 18, height: 12, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 18, y: 22, width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 20, y: 32, width: 10, height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 8,  width: 14, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 8,  width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 0,  width: 14, height: 8,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 8,  width: 8,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-W-30x40-Vastu',
    bhkType: '2BHK', style: 'Vastu Classic', facing: 'W',
    plotWidth: 30, plotHeight: 40, vastuScore: 71,
    tags: ['west-facing', 'vastu', '2bhk'],
    description: 'West-facing 2BHK Vastu layout. Entrance west wall mid, Pooja NE, Kitchen SE, Master SW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 16, width: 6,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 6,  y: 10, width: 16, height: 14, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 22, y: 8,  width: 8,  height: 12, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 22, y: 20, width: 8,  height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 24, width: 14, height: 12, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 26, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 6,  y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 34, width: 8,  height: 6,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 32, width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-25x50-SouthIndian',
    bhkType: '2BHK', style: 'Traditional', facing: 'N',
    plotWidth: 25, plotHeight: 50, vastuScore: 76,
    tags: ['north-facing', 'south-indian', 'traditional', 'courtyard', 'kerala'],
    description: 'South Indian traditional 2BHK on 25×50ft. Full-width verandah, inner muttram (courtyard), rear utility.',
    rooms: [
      { name: 'Front Verandah',   type: 'foyer',          x: 0,  y: 0,  width: 25, height: 5,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 17, y: 5,  width: 8,  height: 7,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 5,  width: 17, height: 12, floor: 1 },
      { name: 'Inner Courtyard',  type: 'courtyard',      x: 7,  y: 17, width: 11, height: 8,  floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 17, width: 7,  height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 18, y: 17, width: 7,  height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 27, width: 14, height: 12, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 29, width: 7,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 39, width: 14, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 39, width: 7,  height: 8,  floor: 1 },
      { name: 'Store',            type: 'storage',        x: 21, y: 29, width: 4,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-E-30x45-Contemporary',
    bhkType: '2BHK', style: 'Contemporary', facing: 'E',
    plotWidth: 30, plotHeight: 45, vastuScore: 74,
    tags: ['east-facing', 'contemporary', '2bhk', 'study'],
    description: 'Contemporary east-facing 2BHK on 30×45ft with home study nook. Master suite at SW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 24, y: 18, width: 6,  height: 9,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 6,  y: 12, width: 18, height: 16, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 10, width: 6,  height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 24, width: 6,  height: 14, floor: 1 },
      { name: 'Study',            type: 'study',          x: 6,  y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 6,  y: 28, width: 18, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 0,  y: 38, width: 6,  height: 7,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 18, y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 24, y: 10, width: 6,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 0,  width: 6,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-30x40-Traditional',
    bhkType: '2BHK', style: 'Traditional', facing: 'N',
    plotWidth: 30, plotHeight: 40, vastuScore: 75,
    tags: ['north-facing', 'traditional', '2bhk', 'verandah', 'north-indian'],
    description: 'North Indian traditional 2BHK. Full-width front verandah, Pooja at NE, large central living.',
    rooms: [
      { name: 'Verandah',         type: 'foyer',          x: 0,  y: 0,  width: 30, height: 5,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 5,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 5,  width: 22, height: 12, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 17, width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 18, y: 17, width: 12, height: 10, floor: 1 },
      { name: 'Store',            type: 'storage',        x: 12, y: 17, width: 6,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 27, width: 14, height: 13, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 27, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 22, y: 27, width: 8,  height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 35, width: 8,  height: 5,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 37, width: 8,  height: 3,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-35x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 35, plotHeight: 40, vastuScore: 77,
    tags: ['north-facing', 'wide-plot', 'modern', '2bhk', 'master-suite'],
    description: 'Wide-plot 2BHK on 35×40ft. Generous master suite with wardrobe, open dining-kitchen, Pooja at NE.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 13, y: 0,  width: 10, height: 5,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 27, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 5,  width: 22, height: 14, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 22, y: 5,  width: 13, height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 22, y: 15, width: 13, height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 19, width: 16, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 16, y: 19, width: 8,  height: 8,  floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 16, y: 27, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 33, width: 14, height: 7,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 33, width: 8,  height: 7,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 33, width: 13, height: 7,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-W-30x50-Contemporary',
    bhkType: '2BHK', style: 'Contemporary', facing: 'W',
    plotWidth: 30, plotHeight: 50, vastuScore: 70,
    tags: ['west-facing', 'contemporary', '2bhk', 'long-plot', 'home-office'],
    description: 'West-facing 2BHK on 30×50ft long plot. Study/home office, open-plan living, master at SW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 21, width: 6,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 6,  y: 14, width: 16, height: 16, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 22, y: 8,  width: 8,  height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 22, y: 22, width: 8,  height: 14, floor: 1 },
      { name: 'Study',            type: 'study',          x: 6,  y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 30, width: 14, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 30, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 44, width: 14, height: 6,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 44, width: 8,  height: 6,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 44, width: 8,  height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-E-30x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'E',
    plotWidth: 30, plotHeight: 40, vastuScore: 73,
    tags: ['east-facing', 'modern', '2bhk', 'open-plan'],
    description: 'Modern east-facing 2BHK. Open kitchen-dining at west side, bedrooms at NW-SW, Pooja at NE.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 24, y: 16, width: 6,  height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 8,  y: 12, width: 16, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 22, width: 8,  height: 12, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 10, width: 8,  height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 8,  y: 26, width: 16, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 0,  y: 34, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 8,  y: 0,  width: 14, height: 12, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 22, y: 8,  width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 0,  width: 8,  height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-30x40-Minimalist',
    bhkType: '2BHK', style: 'Minimalist', facing: 'N',
    plotWidth: 30, plotHeight: 40, vastuScore: 74,
    tags: ['north-facing', 'minimalist', 'japanese', '2bhk', 'clean-lines'],
    description: 'Japanese-minimalist 2BHK. Barrier-free open living zone, sleeping zone separated by sliding partitions.',
    rooms: [
      { name: 'Entry',            type: 'foyer',          x: 11, y: 0,  width: 8,  height: 4,  floor: 1 },
      { name: 'Open Living',      type: 'living_room',    x: 0,  y: 4,  width: 30, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 18, y: 18, width: 12, height: 10, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 18, width: 16, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 16, y: 18, width: 8,  height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 32, width: 14, height: 8,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 32, width: 8,  height: 8,  floor: 1 },
      { name: 'Storage',          type: 'storage',        x: 22, y: 32, width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-30x30-Compact',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 30, plotHeight: 30, vastuScore: 73,
    tags: ['north-facing', 'compact', 'square-plot', '2bhk', 'urban'],
    description: 'Efficient 2BHK on 30×30ft square plot. Every sqft used — no corridors, direct room access.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 10, y: 0,  width: 10, height: 5,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 5,  width: 18, height: 9,  floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 18, y: 5,  width: 12, height: 9,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 14, width: 14, height: 8,  floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 14, width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 22, y: 14, width: 8,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 22, width: 14, height: 8,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 22, width: 8,  height: 8,  floor: 1 },
      { name: 'Storage',          type: 'storage',        x: 22, y: 22, width: 8,  height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-E-25x50-SouthIndian',
    bhkType: '2BHK', style: 'Traditional', facing: 'E',
    plotWidth: 25, plotHeight: 50, vastuScore: 78,
    tags: ['east-facing', 'south-indian', 'traditional', 'narrow', 'courtyard', 'andhra'],
    description: 'South Indian narrow-plot 2BHK. East entrance verandah, inner courtyard, rear utility yard.',
    rooms: [
      { name: 'Verandah',         type: 'foyer',          x: 18, y: 18, width: 7,  height: 14, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 18, y: 0,  width: 7,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 6,  y: 10, width: 12, height: 16, floor: 1 },
      { name: 'Inner Courtyard',  type: 'courtyard',      x: 6,  y: 26, width: 12, height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 6,  y: 36, width: 12, height: 10, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 18, y: 32, width: 7,  height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 30, width: 6,  height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 0,  y: 44, width: 6,  height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 8,  width: 6,  height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 0,  width: 6,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 18, y: 44, width: 7,  height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-S-25x45-Vastu',
    bhkType: '2BHK', style: 'Vastu Classic', facing: 'S',
    plotWidth: 25, plotHeight: 45, vastuScore: 67,
    tags: ['south-facing', 'vastu', '2bhk', 'adaptable'],
    description: 'South-facing 2BHK with Vastu adaptations. Vitatha entrance offset per Vastu for south-facing plots.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 8,  y: 39, width: 9,  height: 6,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 18, y: 0,  width: 7,  height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 27, width: 16, height: 12, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 16, y: 27, width: 9,  height: 10, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 16, y: 37, width: 9,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 13, width: 14, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 14, y: 13, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 0,  width: 14, height: 13, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 39, width: 8,  height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-2BHK-N-40x40-SouthIndian-Courtyard',
    bhkType: '2BHK', style: 'Traditional', facing: 'N',
    plotWidth: 40, plotHeight: 40, vastuScore: 79,
    tags: ['north-facing', 'south-indian', 'courtyard', 'traditional', 'square-plot', 'tamil-nadu'],
    description: 'Tamil Nadu traditional 2BHK on 40×40ft. Central thinnai (outer sitting), inner agraharam-style courtyard.',
    rooms: [
      { name: 'Thinnai',          type: 'foyer',          x: 0,  y: 0,  width: 40, height: 6,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 28, y: 6,  width: 12, height: 8,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 6,  width: 28, height: 12, floor: 1 },
      { name: 'Inner Courtyard',  type: 'courtyard',      x: 12, y: 18, width: 16, height: 10, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 18, width: 12, height: 12, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 28, y: 18, width: 12, height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 30, width: 16, height: 10, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 16, y: 30, width: 8,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 24, y: 30, width: 16, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 16, y: 38, width: 8,  height: 2,  floor: 1 },
      { name: 'Store',            type: 'storage',        x: 28, y: 14, width: 12, height: 4,  floor: 1 },
    ],
  },
]

async function main() {
  console.log(`Seeding batch 2: ${batch2.length} templates…`)
  for (const t of batch2) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: { vastuScore: t.vastuScore, rooms: t.rooms, tags: t.tags, description: t.description },
      create: { ...t, plotUnit: 'ft', isPublic: true, useCount: 0 },
    })
    console.log(`  ✓ ${t.id}`)
  }
  console.log(`\nBatch 2 complete: ${batch2.length} templates`)
}

main().catch(console.error).finally(() => db.$disconnect())
