/**
 * Batch 4: 4BHK new (9) + Villa new (8) = 17 templates
 */
import { PrismaClient } from '@prisma/client'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws
const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const batch4 = [
  // ── 4BHK ────────────────────────────────────────────────────────────────
  {
    id: 'template-4BHK-E-50x80-Vastu',
    bhkType: '4BHK', style: 'Vastu Classic', facing: 'E',
    plotWidth: 50, plotHeight: 80, vastuScore: 87,
    tags: ['east-facing', 'vastu-optimised', '4bhk', 'premium', 'family'],
    description: 'Highest-scoring 4BHK east-facing Vastu layout. Perfect NE Pooja, SE Kitchen, SW Master, servants quarter at NW.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 42, y: 34, width: 8,  height: 12, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 38, y: 0,  width: 12, height: 12, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 16, y: 22, width: 26, height: 22, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 18, width: 16, height: 20, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 0,  y: 38, width: 16, height: 20, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 16, y: 44, width: 22, height: 22, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 38, y: 46, width: 12, height: 12, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 38, y: 58, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 16, y: 0,  width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 16, height: 18, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 16, y: 66, width: 20, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 34, y: 12, width: 16, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 0,  y: 58, width: 16, height: 10, floor: 1 },
      { name: 'Study',            type: 'study',          x: 36, y: 66, width: 14, height: 14, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 0,  y: 68, width: 16, height: 12, floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 38, y: 24, width: 12, height: 12, floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-N-60x80-Traditional',
    bhkType: '4BHK', style: 'Traditional', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 80,
    tags: ['north-facing', 'traditional', '4bhk', 'haveli', 'joint-family'],
    description: 'Joint-family traditional 4BHK on 60×80ft. Separate guest quarters, large chowk, staff room.',
    rooms: [
      { name: 'Verandah',         type: 'foyer',          x: 0,  y: 0,  width: 60, height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 46, y: 8,  width: 14, height: 12, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 8,  width: 30, height: 18, floor: 1 },
      { name: 'Inner Courtyard',  type: 'courtyard',      x: 20, y: 26, width: 20, height: 14, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 0,  y: 26, width: 20, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 40, y: 26, width: 20, height: 14, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 42, width: 20, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 20, y: 42, width: 10, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 20, y: 52, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 60, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 60, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 32, y: 60, width: 16, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 48, y: 60, width: 12, height: 10, floor: 1 },
      { name: 'Staff Room',       type: 'bedroom',        x: 40, y: 42, width: 14, height: 10, floor: 1 },
      { name: 'Staff Bathroom',   type: 'bathroom',       x: 40, y: 52, width: 14, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 54, y: 42, width: 6,  height: 10, floor: 1 },
      { name: 'Staircase',        type: 'staircase',      x: 30, y: 8,  width: 16, height: 12, floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-S-50x80-Contemporary',
    bhkType: '4BHK', style: 'Contemporary', facing: 'S',
    plotWidth: 50, plotHeight: 80, vastuScore: 70,
    tags: ['south-facing', 'contemporary', '4bhk', 'family', 'home-theatre'],
    description: '4BHK south-facing 50×80ft with home theatre, gym room, and rooftop staircase.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 20, y: 74, width: 10, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 56, width: 28, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 28, y: 56, width: 22, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 28, y: 72, width: 22, height: 8,  floor: 1 },
      { name: 'Home Theatre',     type: 'living_room',    x: 0,  y: 72, width: 20, height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 38, width: 22, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 38, width: 12, height: 10, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 22, y: 48, width: 12, height: 8,  floor: 1 },
      { name: 'Gym',              type: 'study',          x: 34, y: 38, width: 16, height: 16, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 20, width: 16, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 20, width: 16, height: 18, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 32, y: 20, width: 18, height: 18, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 8,  width: 12, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 12, y: 8,  width: 12, height: 12, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 36, y: 0,  width: 14, height: 14, floor: 1 },
      { name: 'Study',            type: 'study',          x: 24, y: 0,  width: 12, height: 12, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 34, y: 54, width: 16, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-W-60x70-Modern',
    bhkType: '4BHK', style: 'Modern', facing: 'W',
    plotWidth: 60, plotHeight: 70, vastuScore: 75,
    tags: ['west-facing', 'modern', '4bhk', 'family', 'pool-friendly'],
    description: '4BHK west-facing 60×70ft with large rear garden zone, study/library, and 2-car garage.',
    rooms: [
      { name: 'Foyer',            type: 'foyer',          x: 0,  y: 28, width: 8,  height: 14, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 46, y: 0,  width: 14, height: 12, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 8,  y: 20, width: 28, height: 22, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 36, y: 12, width: 16, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 36, y: 30, width: 16, height: 16, floor: 1 },
      { name: 'Library',          type: 'study',          x: 8,  y: 0,  width: 18, height: 14, floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 36, y: 46, width: 24, height: 16, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 42, width: 22, height: 20, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 42, width: 12, height: 12, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 22, y: 54, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 0,  width: 14, height: 20, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 26, y: 0,  width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 0,  y: 62, width: 18, height: 8,  floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 14, y: 0,  width: 12, height: 14, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 18, y: 62, width: 12, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 34, y: 62, width: 14, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-N-50x80-SouthIndian',
    bhkType: '4BHK', style: 'Traditional', facing: 'N',
    plotWidth: 50, plotHeight: 80, vastuScore: 82,
    tags: ['north-facing', 'south-indian', 'traditional', '4bhk', 'nalukettu', 'courtyard'],
    description: 'Nalukettu-inspired 4BHK on 50×80ft. Four wings around central courtyard, traditional Kerala layout.',
    rooms: [
      { name: 'Padippura',        type: 'foyer',          x: 15, y: 0,  width: 20, height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 38, y: 8,  width: 12, height: 12, floor: 1 },
      { name: 'Vadakkini (N Living)', type: 'living_room', x: 10, y: 8,  width: 28, height: 18, floor: 1 },
      { name: 'Central Courtyard',type: 'courtyard',      x: 15, y: 26, width: 20, height: 16, floor: 1 },
      { name: 'Padinjattini (W Wing)', type: 'living_room', x: 0, y: 26, width: 15, height: 20, floor: 1 },
      { name: 'Kizhakkini (E Wing)', type: 'dining_room', x: 35, y: 26, width: 15, height: 20, floor: 1 },
      { name: 'Thekkinni (S Dining)', type: 'dining_room', x: 10, y: 42, width: 30, height: 14, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 35, y: 46, width: 15, height: 14, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 46, width: 18, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 18, y: 56, width: 10, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 64, width: 16, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 64, width: 16, height: 16, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 32, y: 64, width: 18, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 8,  width: 10, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 28, y: 56, width: 10, height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 38, y: 60, width: 12, height: 10, floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-N-50x90-Luxury',
    bhkType: '4BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 50, plotHeight: 90, vastuScore: 83,
    tags: ['north-facing', 'luxury', '4bhk', 'spa', 'home-theatre', 'pool'],
    description: 'Luxury 4BHK on 50×90ft. Private spa-bathroom, home theatre, gym, pool deck at rear.',
    rooms: [
      { name: 'Grand Foyer',      type: 'foyer',          x: 18, y: 0,  width: 14, height: 8,  floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 38, y: 0,  width: 12, height: 10, floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 8,  width: 30, height: 20, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 30, y: 8,  width: 20, height: 16, floor: 1 },
      { name: 'Gourmet Kitchen',  type: 'kitchen',        x: 30, y: 24, width: 20, height: 16, floor: 1 },
      { name: 'Home Theatre',     type: 'living_room',    x: 0,  y: 28, width: 20, height: 14, floor: 1 },
      { name: 'Gym',              type: 'study',          x: 20, y: 28, width: 14, height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 42, width: 22, height: 20, floor: 1 },
      { name: 'Master Spa Bath',  type: 'bathroom',       x: 22, y: 42, width: 12, height: 12, floor: 1 },
      { name: 'Walk-in Wardrobe', type: 'storage',        x: 22, y: 54, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 62, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 18, y: 62, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 36, y: 62, width: 14, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 34, y: 40, width: 16, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 0,  y: 78, width: 12, height: 12, floor: 1 },
      { name: 'Pool Deck',        type: 'courtyard',      x: 12, y: 78, width: 26, height: 12, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 38, y: 78, width: 12, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-N-60x80-NorthIndian',
    bhkType: '4BHK', style: 'Traditional', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 78,
    tags: ['north-facing', 'north-indian', 'traditional', 'haveli', '4bhk', 'rajasthani'],
    description: 'Rajasthani Haveli-inspired 4BHK. Ornate dalan, large chowk, separate zenana quarters, merchant-style store.',
    rooms: [
      { name: 'Dalan (Verandah)', type: 'foyer',          x: 0,  y: 0,  width: 60, height: 8,  floor: 1 },
      { name: 'Pooja Ghar',       type: 'pooja_room',     x: 46, y: 8,  width: 14, height: 14, floor: 1 },
      { name: 'Baithak',          type: 'living_room',    x: 0,  y: 8,  width: 30, height: 20, floor: 1 },
      { name: 'Chowk',            type: 'courtyard',      x: 20, y: 28, width: 20, height: 16, floor: 1 },
      { name: 'Bhojankaksha',     type: 'dining_room',    x: 0,  y: 28, width: 20, height: 16, floor: 1 },
      { name: 'Rasoi',            type: 'kitchen',        x: 40, y: 28, width: 20, height: 16, floor: 1 },
      { name: 'Kothri (Store)',   type: 'storage',        x: 30, y: 8,  width: 16, height: 12, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 44, width: 20, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 20, y: 44, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 62, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 16, y: 62, width: 16, height: 14, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 32, y: 62, width: 16, height: 14, floor: 1 },
      { name: 'Zenana Baithak',   type: 'living_room',    x: 30, y: 44, width: 16, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 48, y: 44, width: 12, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 48, y: 62, width: 12, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 40, y: 56, width: 20, height: 6,  floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-N-60x70-Minimalist',
    bhkType: '4BHK', style: 'Minimalist', facing: 'N',
    plotWidth: 60, plotHeight: 70, vastuScore: 77,
    tags: ['north-facing', 'minimalist', '4bhk', 'modern', 'clean-lines'],
    description: 'Minimalist 4BHK on 60×70ft. Large open-plan living-dining, private sleeping wing, hidden storage throughout.',
    rooms: [
      { name: 'Entry',            type: 'foyer',          x: 22, y: 0,  width: 16, height: 6,  floor: 1 },
      { name: 'Open Living',      type: 'living_room',    x: 0,  y: 6,  width: 60, height: 22, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 40, y: 28, width: 20, height: 16, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 28, width: 22, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 28, width: 10, height: 12, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 22, y: 40, width: 10, height: 6,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 46, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 18, y: 46, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 36, y: 46, width: 18, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 32, y: 28, width: 12, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 0,  y: 62, width: 14, height: 8,  floor: 1 },
      { name: 'Storage',          type: 'storage',        x: 54, y: 62, width: 6,  height: 8,  floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 44, y: 44, width: 16, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-4BHK-E-60x80-SouthIndian',
    bhkType: '4BHK', style: 'Traditional', facing: 'E',
    plotWidth: 60, plotHeight: 80, vastuScore: 85,
    tags: ['east-facing', 'south-indian', '4bhk', 'traditional', 'vastu', 'tamil-nadu'],
    description: 'Grand Tamil Nadu-style 4BHK east-facing. Gated entrance, pillared verandah, multiple courtyards, separate kitchen wing.',
    rooms: [
      { name: 'Thinnai',          type: 'foyer',          x: 48, y: 28, width: 12, height: 24, floor: 1 },
      { name: 'Pooja Room',       type: 'pooja_room',     x: 48, y: 0,  width: 12, height: 14, floor: 1 },
      { name: 'Mukha Mantapam',   type: 'living_room',    x: 16, y: 20, width: 32, height: 24, floor: 1 },
      { name: 'Mutram (Courtyard)', type: 'courtyard',    x: 16, y: 44, width: 24, height: 18, floor: 1 },
      { name: 'Adukkala (Kitchen)', type: 'kitchen',      x: 0,  y: 38, width: 16, height: 22, floor: 1 },
      { name: 'Dining Hall',      type: 'dining_room',    x: 0,  y: 16, width: 16, height: 22, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 16, y: 62, width: 22, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 38, y: 62, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 16, y: 0,  width: 18, height: 20, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 0,  y: 0,  width: 16, height: 16, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 38, y: 52, width: 22, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 34, y: 14, width: 14, height: 12, floor: 1 },
      { name: 'Bathroom 3',       type: 'bathroom',       x: 0,  y: 60, width: 16, height: 10, floor: 1 },
      { name: 'Store',            type: 'storage',        x: 48, y: 52, width: 12, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 48, y: 14, width: 12, height: 14, floor: 1 },
    ],
  },

  // ── VILLA NEW VARIANTS ───────────────────────────────────────────────────
  {
    id: 'template-VILLA-N-80x100-Modern',
    bhkType: 'VILLA', style: 'Modern', facing: 'N',
    plotWidth: 80, plotHeight: 100, vastuScore: 85,
    tags: ['north-facing', 'villa', 'luxury', 'modern', 'multi-floor', 'pool'],
    description: 'Grand modern villa on 80×100ft north-facing plot. Ground: entertainment + guest. First: family suites. Pool at rear.',
    rooms: [
      // Ground floor
      { name: 'Grand Foyer',       type: 'foyer',          x: 28, y: 0,  width: 24, height: 8,  floor: 1 },
      { name: 'Pooja Room',        type: 'pooja_room',     x: 62, y: 0,  width: 18, height: 14, floor: 1 },
      { name: 'Living Room',       type: 'living_room',    x: 0,  y: 8,  width: 40, height: 24, floor: 1 },
      { name: 'Dining Room',       type: 'dining_room',    x: 40, y: 8,  width: 28, height: 20, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 40, y: 28, width: 28, height: 20, floor: 1 },
      { name: 'Home Theatre',      type: 'living_room',    x: 0,  y: 32, width: 24, height: 18, floor: 1 },
      { name: 'Guest Bedroom',     type: 'bedroom',        x: 24, y: 32, width: 16, height: 16, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 68, y: 14, width: 12, height: 10, floor: 1 },
      { name: 'Garage',            type: 'garage',         x: 0,  y: 50, width: 28, height: 22, floor: 1 },
      { name: 'Staff Quarters',    type: 'bedroom',        x: 28, y: 48, width: 14, height: 14, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 42, y: 48, width: 14, height: 12, floor: 1 },
      { name: 'Pool Deck',         type: 'courtyard',      x: 0,  y: 72, width: 80, height: 18, floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 56, y: 48, width: 14, height: 14, floor: 1 },
      // First floor
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 0,  width: 28, height: 26, floor: 2 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 28, y: 0,  width: 14, height: 14, floor: 2 },
      { name: 'Walk-in Wardrobe',  type: 'storage',        x: 28, y: 14, width: 14, height: 12, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 42, y: 0,  width: 20, height: 20, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 62, y: 0,  width: 18, height: 20, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 42, y: 20, width: 20, height: 18, floor: 2 },
      { name: 'Bedroom 5',         type: 'bedroom',        x: 62, y: 20, width: 18, height: 18, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 0,  y: 26, width: 14, height: 10, floor: 2 },
      { name: 'Bathroom 3',        type: 'bathroom',       x: 14, y: 26, width: 14, height: 10, floor: 2 },
      { name: 'Family Lounge',     type: 'living_room',    x: 0,  y: 36, width: 30, height: 18, floor: 2 },
      { name: 'Study',             type: 'study',          x: 30, y: 36, width: 16, height: 14, floor: 2 },
      { name: 'Terrace',           type: 'courtyard',      x: 46, y: 38, width: 34, height: 22, floor: 2 },
    ],
  },
  {
    id: 'template-VILLA-E-70x90-Vastu',
    bhkType: 'VILLA', style: 'Vastu Classic', facing: 'E',
    plotWidth: 70, plotHeight: 90, vastuScore: 90,
    tags: ['east-facing', 'villa', 'vastu-optimised', 'luxury', 'premium'],
    description: 'Highest-scoring villa: east-facing 70×90ft with perfect Vastu zoning. Double courtyard, grand thinnai, zenana wing.',
    rooms: [
      // Ground floor
      { name: 'Grand Thinnai',     type: 'foyer',          x: 58, y: 30, width: 12, height: 30, floor: 1 },
      { name: 'Pooja Room',        type: 'pooja_room',     x: 56, y: 0,  width: 14, height: 14, floor: 1 },
      { name: 'Main Living',       type: 'living_room',    x: 20, y: 20, width: 38, height: 28, floor: 1 },
      { name: 'North Courtyard',   type: 'courtyard',      x: 20, y: 48, width: 22, height: 18, floor: 1 },
      { name: 'Dining Hall',       type: 'dining_room',    x: 0,  y: 14, width: 20, height: 22, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 0,  y: 36, width: 20, height: 24, floor: 1 },
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 20, y: 66, width: 28, height: 24, floor: 1 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 48, y: 66, width: 14, height: 14, floor: 1 },
      { name: 'Master Wardrobe',   type: 'storage',        x: 48, y: 80, width: 14, height: 10, floor: 1 },
      { name: 'Guest Suite',       type: 'bedroom',        x: 0,  y: 60, width: 20, height: 18, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 0,  y: 78, width: 10, height: 12, floor: 1 },
      { name: 'Staff Room',        type: 'bedroom',        x: 42, y: 48, width: 16, height: 14, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 42, y: 62, width: 16, height: 8,  floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 58, y: 60, width: 12, height: 14, floor: 1 },
      // First floor
      { name: 'Family Lounge',     type: 'living_room',    x: 20, y: 0,  width: 36, height: 20, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 0,  y: 0,  width: 20, height: 22, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 56, y: 0,  width: 14, height: 18, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 20, y: 20, width: 20, height: 20, floor: 2 },
      { name: 'Bedroom 5',         type: 'bedroom',        x: 40, y: 20, width: 20, height: 20, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 0,  y: 22, width: 20, height: 12, floor: 2 },
      { name: 'Bathroom 3',        type: 'bathroom',       x: 60, y: 18, width: 10, height: 12, floor: 2 },
      { name: 'Study/Library',     type: 'study',          x: 20, y: 40, width: 20, height: 16, floor: 2 },
      { name: 'Sky Courtyard',     type: 'courtyard',      x: 40, y: 40, width: 30, height: 20, floor: 2 },
    ],
  },
  {
    id: 'template-VILLA-S-60x80-Mediterranean',
    bhkType: 'VILLA', style: 'Contemporary', facing: 'S',
    plotWidth: 60, plotHeight: 80, vastuScore: 73,
    tags: ['south-facing', 'villa', 'mediterranean', 'pool', 'luxury', 'western'],
    description: 'Mediterranean-style villa on 60×80ft. Arched colonnade, infinity pool at south end, open-plan interiors.',
    rooms: [
      // Ground floor
      { name: 'Colonnade Entry',   type: 'foyer',          x: 22, y: 72, width: 16, height: 8,  floor: 1 },
      { name: 'Grand Living',      type: 'living_room',    x: 0,  y: 52, width: 36, height: 20, floor: 1 },
      { name: 'Dining Room',       type: 'dining_room',    x: 36, y: 52, width: 24, height: 16, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 36, y: 68, width: 24, height: 12, floor: 1 },
      { name: 'Infinity Pool',     type: 'courtyard',      x: 0,  y: 68, width: 36, height: 12, floor: 1 },
      { name: 'Master Suite',      type: 'master_bedroom', x: 0,  y: 34, width: 24, height: 18, floor: 1 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 24, y: 34, width: 12, height: 12, floor: 1 },
      { name: 'Dressing Room',     type: 'storage',        x: 24, y: 46, width: 12, height: 6,  floor: 1 },
      { name: 'Guest Bedroom',     type: 'bedroom',        x: 36, y: 34, width: 18, height: 16, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 54, y: 34, width: 6,  height: 16, floor: 1 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 0,  y: 18, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 18, y: 18, width: 18, height: 16, floor: 1 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 36, y: 18, width: 12, height: 12, floor: 1 },
      { name: 'Pooja/Chapel',      type: 'pooja_room',     x: 48, y: 18, width: 12, height: 12, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 36, y: 50, width: 18, height: 2,  floor: 1 },
      { name: 'Study',             type: 'study',          x: 0,  y: 0,  width: 20, height: 18, floor: 1 },
      { name: 'Library',           type: 'study',          x: 20, y: 0,  width: 20, height: 18, floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 40, y: 0,  width: 14, height: 14, floor: 1 },
    ],
  },
  {
    id: 'template-VILLA-N-80x100-Ranch',
    bhkType: 'VILLA', style: 'Contemporary', facing: 'N',
    plotWidth: 80, plotHeight: 100, vastuScore: 72,
    tags: ['north-facing', 'villa', 'ranch', 'single-floor', 'western', 'open-plan'],
    description: 'American ranch-style single-floor villa on 80×100ft. All rooms on one level, U-shaped layout, wrap-around porch.',
    rooms: [
      { name: 'Porch',             type: 'foyer',          x: 20, y: 0,  width: 40, height: 8,  floor: 1 },
      { name: 'Great Room',        type: 'living_room',    x: 0,  y: 8,  width: 50, height: 24, floor: 1 },
      { name: 'Dining Room',       type: 'dining_room',    x: 50, y: 8,  width: 30, height: 18, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 50, y: 26, width: 30, height: 20, floor: 1 },
      { name: 'Mudroom',           type: 'foyer',          x: 50, y: 46, width: 14, height: 10, floor: 1 },
      { name: 'Garage',            type: 'garage',         x: 50, y: 56, width: 30, height: 24, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 50, y: 80, width: 16, height: 12, floor: 1 },
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 32, width: 22, height: 22, floor: 1 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 22, y: 32, width: 12, height: 14, floor: 1 },
      { name: 'Master Wardrobe',   type: 'storage',        x: 22, y: 46, width: 12, height: 10, floor: 1 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 0,  y: 54, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 18, y: 54, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 0,  y: 72, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 5',         type: 'bedroom',        x: 18, y: 72, width: 18, height: 18, floor: 1 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 36, y: 54, width: 14, height: 12, floor: 1 },
      { name: 'Bathroom 3',        type: 'bathroom',       x: 36, y: 66, width: 14, height: 10, floor: 1 },
      { name: 'Study',             type: 'study',          x: 34, y: 32, width: 16, height: 14, floor: 1 },
      { name: 'Rear Garden',       type: 'courtyard',      x: 66, y: 80, width: 14, height: 20, floor: 1 },
    ],
  },
  {
    id: 'template-VILLA-N-80x100-Colonial',
    bhkType: 'VILLA', style: 'Traditional', facing: 'N',
    plotWidth: 80, plotHeight: 100, vastuScore: 76,
    tags: ['north-facing', 'villa', 'colonial', '2-story', 'western', 'symmetrical'],
    description: '2-story colonial villa on 80×100ft. Symmetrical facade, central staircase, formal rooms ground floor, bedrooms first.',
    rooms: [
      // Ground floor - formal rooms
      { name: 'Entry Hall',        type: 'foyer',          x: 30, y: 0,  width: 20, height: 10, floor: 1 },
      { name: 'Formal Living',     type: 'living_room',    x: 0,  y: 10, width: 30, height: 22, floor: 1 },
      { name: 'Formal Dining',     type: 'dining_room',    x: 50, y: 10, width: 30, height: 22, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 46, y: 32, width: 34, height: 20, floor: 1 },
      { name: 'Family Room',       type: 'living_room',    x: 0,  y: 32, width: 30, height: 20, floor: 1 },
      { name: 'Library',           type: 'study',          x: 30, y: 32, width: 16, height: 14, floor: 1 },
      { name: 'Study',             type: 'study',          x: 30, y: 46, width: 16, height: 10, floor: 1 },
      { name: 'Powder Room',       type: 'bathroom',       x: 0,  y: 52, width: 12, height: 8,  floor: 1 },
      { name: 'Garage',            type: 'garage',         x: 0,  y: 60, width: 28, height: 22, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 28, y: 56, width: 18, height: 14, floor: 1 },
      { name: 'Guest Suite',       type: 'bedroom',        x: 46, y: 52, width: 22, height: 16, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 68, y: 52, width: 12, height: 12, floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 30, y: 10, width: 20, height: 16, floor: 1 },
      // First floor - bedrooms
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 0,  width: 28, height: 26, floor: 2 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 28, y: 0,  width: 14, height: 14, floor: 2 },
      { name: 'Walk-in Wardrobe',  type: 'storage',        x: 28, y: 14, width: 14, height: 12, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 42, y: 0,  width: 22, height: 22, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 64, y: 0,  width: 16, height: 22, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 42, y: 22, width: 22, height: 20, floor: 2 },
      { name: 'Bedroom 5',         type: 'bedroom',        x: 64, y: 22, width: 16, height: 20, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 0,  y: 26, width: 14, height: 12, floor: 2 },
      { name: 'Bathroom 3',        type: 'bathroom',       x: 14, y: 26, width: 14, height: 12, floor: 2 },
      { name: 'Upper Hall',        type: 'foyer',          x: 28, y: 26, width: 14, height: 8,  floor: 2 },
      { name: 'Sitting Room',      type: 'living_room',    x: 0,  y: 38, width: 42, height: 20, floor: 2 },
    ],
  },
  {
    id: 'template-VILLA-N-80x90-NorthIndian',
    bhkType: 'VILLA', style: 'Traditional', facing: 'N',
    plotWidth: 80, plotHeight: 90, vastuScore: 81,
    tags: ['north-facing', 'villa', 'north-indian', 'haveli', 'traditional', 'multi-floor', 'joint-family'],
    description: 'Grand North Indian Haveli villa on 80×90ft. Multiple courtyards, zenana-mardana separation, ornate baithak.',
    rooms: [
      // Ground floor
      { name: 'Prangan (Courtyard Gate)', type: 'foyer', x: 28, y: 0,  width: 24, height: 10, floor: 1 },
      { name: 'Pooja Mandir',      type: 'pooja_room',    x: 62, y: 0,  width: 18, height: 16, floor: 1 },
      { name: 'Mardana Baithak',   type: 'living_room',   x: 0,  y: 10, width: 38, height: 24, floor: 1 },
      { name: 'Outer Chowk',       type: 'courtyard',     x: 22, y: 34, width: 24, height: 18, floor: 1 },
      { name: 'Bhojankaksha',      type: 'dining_room',   x: 0,  y: 34, width: 22, height: 20, floor: 1 },
      { name: 'Rasoi',             type: 'kitchen',       x: 46, y: 34, width: 22, height: 20, floor: 1 },
      { name: 'Zenana Living',     type: 'living_room',   x: 38, y: 10, width: 24, height: 24, floor: 1 },
      { name: 'Kothri (Stores)',   type: 'storage',       x: 0,  y: 54, width: 16, height: 16, floor: 1 },
      { name: 'Staff Quarters',    type: 'bedroom',       x: 16, y: 54, width: 16, height: 14, floor: 1 },
      { name: 'Garage',            type: 'garage',        x: 46, y: 54, width: 22, height: 18, floor: 1 },
      { name: 'Inner Chowk',       type: 'courtyard',     x: 22, y: 52, width: 24, height: 18, floor: 1 },
      { name: 'Utility',           type: 'utility',       x: 68, y: 54, width: 12, height: 14, floor: 1 },
      { name: 'Staircase',         type: 'staircase',     x: 62, y: 16, width: 18, height: 18, floor: 1 },
      // First floor
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 0,  width: 24, height: 28, floor: 2 },
      { name: 'Master Bathroom',   type: 'bathroom',      x: 24, y: 0,  width: 14, height: 14, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',       x: 38, y: 0,  width: 22, height: 22, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',       x: 60, y: 0,  width: 20, height: 22, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',       x: 38, y: 22, width: 22, height: 20, floor: 2 },
      { name: 'Bedroom 5',         type: 'bedroom',       x: 60, y: 22, width: 20, height: 20, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',      x: 0,  y: 28, width: 16, height: 12, floor: 2 },
      { name: 'Bathroom 3',        type: 'bathroom',      x: 16, y: 28, width: 14, height: 12, floor: 2 },
      { name: 'Open Terrace',      type: 'courtyard',     x: 0,  y: 40, width: 38, height: 22, floor: 2 },
      { name: 'Sitting Room',      type: 'living_room',   x: 24, y: 14, width: 14, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-VILLA-N-100x120-Grand',
    bhkType: 'VILLA', style: 'Contemporary', facing: 'N',
    plotWidth: 100, plotHeight: 120, vastuScore: 86,
    tags: ['north-facing', 'villa', 'grand', 'luxury', 'multi-floor', 'pool', 'cinema'],
    description: 'Grand 6-bedroom luxury villa on 100×120ft. Home cinema, spa, infinity pool, 2-car garage, staff wing.',
    rooms: [
      // Ground floor
      { name: 'Grand Foyer',       type: 'foyer',          x: 38, y: 0,  width: 24, height: 10, floor: 1 },
      { name: 'Pooja Room',        type: 'pooja_room',     x: 80, y: 0,  width: 20, height: 16, floor: 1 },
      { name: 'Grand Living',      type: 'living_room',    x: 0,  y: 10, width: 50, height: 28, floor: 1 },
      { name: 'Formal Dining',     type: 'dining_room',    x: 50, y: 10, width: 30, height: 22, floor: 1 },
      { name: 'Kitchen',           type: 'kitchen',        x: 50, y: 32, width: 30, height: 22, floor: 1 },
      { name: 'Pantry',            type: 'storage',        x: 80, y: 32, width: 20, height: 14, floor: 1 },
      { name: 'Home Cinema',       type: 'living_room',    x: 0,  y: 38, width: 30, height: 22, floor: 1 },
      { name: 'Gym',               type: 'study',          x: 30, y: 38, width: 20, height: 16, floor: 1 },
      { name: 'Spa',               type: 'bathroom',       x: 30, y: 54, width: 20, height: 14, floor: 1 },
      { name: 'Guest Suite',       type: 'bedroom',        x: 0,  y: 60, width: 20, height: 22, floor: 1 },
      { name: 'Guest Bathroom',    type: 'bathroom',       x: 20, y: 60, width: 10, height: 14, floor: 1 },
      { name: 'Staff Quarters',    type: 'bedroom',        x: 50, y: 54, width: 18, height: 16, floor: 1 },
      { name: 'Staff Bathroom',    type: 'bathroom',       x: 68, y: 54, width: 12, height: 10, floor: 1 },
      { name: 'Garage',            type: 'garage',         x: 80, y: 46, width: 20, height: 28, floor: 1 },
      { name: 'Utility',           type: 'utility',        x: 68, y: 64, width: 12, height: 14, floor: 1 },
      { name: 'Pool',              type: 'courtyard',      x: 0,  y: 82, width: 100, height: 28, floor: 1 },
      { name: 'Staircase',         type: 'staircase',      x: 50, y: 70, width: 18, height: 14, floor: 1 },
      // First floor
      { name: 'Master Bedroom',    type: 'master_bedroom', x: 0,  y: 0,  width: 32, height: 30, floor: 2 },
      { name: 'Master Bathroom',   type: 'bathroom',       x: 32, y: 0,  width: 16, height: 16, floor: 2 },
      { name: 'Walk-in Wardrobe',  type: 'storage',        x: 32, y: 16, width: 16, height: 14, floor: 2 },
      { name: 'Bedroom 2',         type: 'bedroom',        x: 48, y: 0,  width: 24, height: 24, floor: 2 },
      { name: 'Bedroom 3',         type: 'bedroom',        x: 72, y: 0,  width: 28, height: 24, floor: 2 },
      { name: 'Bedroom 4',         type: 'bedroom',        x: 48, y: 24, width: 24, height: 22, floor: 2 },
      { name: 'Bedroom 5',         type: 'bedroom',        x: 72, y: 24, width: 28, height: 22, floor: 2 },
      { name: 'Bedroom 6',         type: 'bedroom',        x: 0,  y: 30, width: 20, height: 22, floor: 2 },
      { name: 'Bathroom 2',        type: 'bathroom',       x: 20, y: 30, width: 12, height: 12, floor: 2 },
      { name: 'Bathroom 3',        type: 'bathroom',       x: 20, y: 42, width: 12, height: 12, floor: 2 },
      { name: 'Family Lounge',     type: 'living_room',    x: 0,  y: 52, width: 48, height: 22, floor: 2 },
      { name: 'Sky Terrace',       type: 'courtyard',      x: 48, y: 46, width: 52, height: 28, floor: 2 },
    ],
  },
]

async function main() {
  console.log(`Seeding batch 4: ${batch4.length} templates…`)
  for (const t of batch4) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: { vastuScore: t.vastuScore, rooms: t.rooms, tags: t.tags, description: t.description },
      create: { ...t, plotUnit: 'ft', isPublic: true, useCount: 0 },
    })
    console.log(`  ✓ ${t.id}`)
  }
  console.log(`\nBatch 4 complete: ${batch4.length} templates`)
}

main().catch(console.error).finally(() => db.$disconnect())
