/**
 * Batch 5: Duplex (6) + Row House (5) + Western styles (6) + Special (4) = 21 templates
 */
import { PrismaClient } from '@prisma/client'
import { neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import ws from 'ws'

neonConfig.webSocketConstructor = ws
const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaNeon({ connectionString })
const db = new PrismaClient({ adapter })

const batch5 = [
  // ── DUPLEX ──────────────────────────────────────────────────────────────
  {
    id: 'template-DUPLEX-N-20x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 20, plotHeight: 40, vastuScore: 74,
    tags: ['north-facing', 'duplex', 'modern', '2-floor', 'compact-plot'],
    description: 'Modern duplex on 20×40ft. Ground: living+kitchen+1 bed. First: 2 beds. Separate entrance possible.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 6,  y: 0,  width: 8,  height: 4,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 4,  width: 12, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 12, y: 4,  width: 8,  height: 10, floor: 1 },
      { name: 'Bedroom 1',       type: 'bedroom',        x: 0,  y: 16, width: 12, height: 12, floor: 1 },
      { name: 'Bathroom 1',      type: 'bathroom',       x: 12, y: 14, width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 12, y: 22, width: 8,  height: 6,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 28, width: 10, height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 12, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 12, y: 0,  width: 8,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 12, y: 8,  width: 8,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 26, width: 20, height: 10, floor: 2 },
    ],
  },
  {
    id: 'template-DUPLEX-E-25x40-Vastu',
    bhkType: '2BHK', style: 'Vastu Classic', facing: 'E',
    plotWidth: 25, plotHeight: 40, vastuScore: 76,
    tags: ['east-facing', 'duplex', 'vastu', '2-floor'],
    description: 'Vastu duplex on 25×40ft east-facing. Pooja NE, kitchen SE on GF; 3 bedrooms on first floor.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 19, y: 16, width: 6,  height: 8,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 18, y: 0,  width: 7,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 6,  y: 10, width: 13, height: 16, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 6,  y: 26, width: 13, height: 12, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 0,  y: 8,  width: 6,  height: 16, floor: 1 },
      { name: 'Bathroom 1',      type: 'bathroom',       x: 0,  y: 24, width: 6,  height: 10, floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 0,  width: 6,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 6,  y: 0,  width: 13, height: 10, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 19, y: 8,  width: 6,  height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 0,  width: 12, height: 14, floor: 2 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 12, y: 0,  width: 13, height: 14, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 0,  y: 14, width: 8,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 8,  y: 14, width: 17, height: 26, floor: 2 },
    ],
  },
  {
    id: 'template-DUPLEX-N-20x50-Traditional',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 20, plotHeight: 50, vastuScore: 73,
    tags: ['north-facing', 'duplex', 'traditional', '3bhk', 'south-indian'],
    description: 'South Indian style duplex on 20×50ft. Ground floor tenantable + first floor owner suite.',
    rooms: [
      { name: 'G.F. Verandah',   type: 'foyer',          x: 0,  y: 0,  width: 20, height: 5,  floor: 1 },
      { name: 'G.F. Living',     type: 'living_room',    x: 0,  y: 5,  width: 12, height: 12, floor: 1 },
      { name: 'G.F. Kitchen',    type: 'kitchen',        x: 12, y: 5,  width: 8,  height: 10, floor: 1 },
      { name: 'G.F. Bedroom',    type: 'bedroom',        x: 0,  y: 17, width: 12, height: 12, floor: 1 },
      { name: 'G.F. Bathroom',   type: 'bathroom',       x: 12, y: 15, width: 8,  height: 8,  floor: 1 },
      { name: 'G.F. Store',      type: 'storage',        x: 12, y: 23, width: 8,  height: 6,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 29, width: 8,  height: 10, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 8,  y: 29, width: 12, height: 8,  floor: 1 },
      { name: 'F.F. Master',     type: 'master_bedroom', x: 0,  y: 0,  width: 14, height: 14, floor: 2 },
      { name: 'F.F. MBath',      type: 'bathroom',       x: 14, y: 0,  width: 6,  height: 8,  floor: 2 },
      { name: 'F.F. Bedroom 2',  type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'F.F. Bedroom 3',  type: 'bedroom',        x: 12, y: 14, width: 8,  height: 12, floor: 2 },
      { name: 'F.F. Bathroom',   type: 'bathroom',       x: 14, y: 8,  width: 6,  height: 6,  floor: 2 },
      { name: 'F.F. Terrace',    type: 'courtyard',      x: 0,  y: 26, width: 20, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-DUPLEX-N-25x45-SouthIndian',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 25, plotHeight: 45, vastuScore: 77,
    tags: ['north-facing', 'duplex', 'south-indian', '3bhk', 'courtyard'],
    description: 'South Indian duplex with shared courtyard. Ground: common rooms + 1 bed. First: 2 beds + master.',
    rooms: [
      { name: 'Verandah',        type: 'foyer',          x: 0,  y: 0,  width: 25, height: 5,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 17, y: 5,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 17, height: 14, floor: 1 },
      { name: 'Inner Courtyard', type: 'courtyard',      x: 6,  y: 19, width: 11, height: 8,  floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 0,  y: 19, width: 6,  height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 17, y: 13, width: 8,  height: 14, floor: 1 },
      { name: 'Bedroom 1',       type: 'bedroom',        x: 0,  y: 29, width: 12, height: 12, floor: 1 },
      { name: 'Bathroom 1',      type: 'bathroom',       x: 12, y: 27, width: 7,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 17, y: 27, width: 8,  height: 10, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 14, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 14, y: 0,  width: 7,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 12, y: 14, width: 13, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 14, y: 8,  width: 7,  height: 6,  floor: 2 },
      { name: 'Open Terrace',    type: 'courtyard',      x: 0,  y: 26, width: 25, height: 15, floor: 2 },
    ],
  },
  {
    id: 'template-DUPLEX-N-30x50-Luxury',
    bhkType: '4BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 30, plotHeight: 50, vastuScore: 80,
    tags: ['north-facing', 'duplex', 'luxury', '4bhk', 'spacious'],
    description: 'Luxury duplex on 30×50ft. Ground floor: entertainment zone. First: 4 bedrooms with ensuite baths.',
    rooms: [
      { name: 'Grand Foyer',     type: 'foyer',          x: 10, y: 0,  width: 10, height: 6,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 22, y: 0,  width: 8,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 20, height: 16, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 20, y: 6,  width: 10, height: 14, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 20, y: 20, width: 10, height: 12, floor: 1 },
      { name: 'Home Office',     type: 'study',          x: 0,  y: 22, width: 12, height: 12, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 12, y: 22, width: 8,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 12, y: 30, width: 8,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 20, y: 32, width: 10, height: 10, floor: 1 },
      { name: 'Rear Garden',     type: 'courtyard',      x: 0,  y: 34, width: 20, height: 16, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 16, height: 16, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 16, y: 0,  width: 8,  height: 10, floor: 2 },
      { name: 'Master Wardrobe', type: 'storage',        x: 16, y: 10, width: 8,  height: 6,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 16, width: 14, height: 14, floor: 2 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 14, y: 16, width: 16, height: 14, floor: 2 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 0,  y: 30, width: 14, height: 14, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 14, y: 30, width: 8,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 22, y: 0,  width: 8,  height: 44, floor: 2 },
    ],
  },
  {
    id: 'template-DUPLEX-W-20x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'W',
    plotWidth: 20, plotHeight: 40, vastuScore: 69,
    tags: ['west-facing', 'duplex', 'modern', '2-floor'],
    description: 'West-facing modern duplex. Ground: living wing. First: sleeping wing. Rooftop terrace.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 0,  y: 16, width: 5,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 5,  y: 10, width: 10, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 5,  y: 22, width: 8,  height: 10, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 13, y: 10, width: 7,  height: 10, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 13, y: 20, width: 7,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 0,  width: 8,  height: 10, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 5,  y: 32, width: 8,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 12, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 12, y: 0,  width: 8,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 12, y: 8,  width: 8,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 26, width: 20, height: 14, floor: 2 },
    ],
  },

  // ── ROW HOUSE ────────────────────────────────────────────────────────────
  {
    id: 'template-ROWHOUSE-N-15x40-Modern',
    bhkType: '2BHK', style: 'Modern', facing: 'N',
    plotWidth: 15, plotHeight: 40, vastuScore: 70,
    tags: ['north-facing', 'row-house', 'narrow-plot', 'modern', 'urban'],
    description: 'Urban row house on 15×40ft narrow plot. Stacked vertical layout, roof terrace, compact but complete.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 3,  y: 0,  width: 9,  height: 4,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 4,  width: 15, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 0,  y: 16, width: 9,  height: 10, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 9,  y: 16, width: 6,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 9,  y: 24, width: 6,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 26, width: 8,  height: 10, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 10, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 10, y: 0,  width: 5,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 10, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 10, y: 8,  width: 5,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 26, width: 15, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-ROWHOUSE-N-18x40-Traditional',
    bhkType: '2BHK', style: 'Traditional', facing: 'N',
    plotWidth: 18, plotHeight: 40, vastuScore: 72,
    tags: ['north-facing', 'row-house', 'traditional', 'narrow', 'south-indian'],
    description: 'South Indian row house on 18×40ft. Front verandah, rear utility, traditional proportions.',
    rooms: [
      { name: 'Verandah',        type: 'foyer',          x: 0,  y: 0,  width: 18, height: 5,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 11, y: 5,  width: 7,  height: 7,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 11, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 0,  y: 17, width: 11, height: 10, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 11, y: 12, width: 7,  height: 10, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 11, y: 22, width: 7,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 0,  y: 27, width: 11, height: 7,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 11, y: 30, width: 7,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 12, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 12, y: 0,  width: 6,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 12, y: 8,  width: 6,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 26, width: 18, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-ROWHOUSE-E-15x45-Vastu',
    bhkType: '2BHK', style: 'Vastu Classic', facing: 'E',
    plotWidth: 15, plotHeight: 45, vastuScore: 74,
    tags: ['east-facing', 'row-house', 'vastu', 'narrow-plot'],
    description: 'Vastu-compliant east-facing row house. Narrow 15×45ft plot, 2-floor, Pooja at NE, Kitchen at SE.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 9,  y: 18, width: 6,  height: 9,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 9,  y: 0,  width: 6,  height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 8,  width: 9,  height: 16, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 0,  y: 24, width: 9,  height: 12, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 9,  y: 27, width: 6,  height: 10, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 0,  y: 36, width: 7,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 0,  width: 6,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 10, height: 16, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 10, y: 0,  width: 5,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 16, width: 10, height: 14, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 10, y: 8,  width: 5,  height: 8,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 30, width: 15, height: 15, floor: 2 },
    ],
  },
  {
    id: 'template-ROWHOUSE-N-20x40-Contemporary',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 20, plotHeight: 40, vastuScore: 76,
    tags: ['north-facing', 'row-house', 'contemporary', '3bhk', 'corner-unit'],
    description: 'Contemporary 3BHK row house on 20×40ft. Corner unit with extra light, study nook, large terrace.',
    rooms: [
      { name: 'Foyer',           type: 'foyer',          x: 6,  y: 0,  width: 8,  height: 5,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 14, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 14, y: 5,  width: 6,  height: 12, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 0,  y: 17, width: 12, height: 10, floor: 1 },
      { name: 'Study',           type: 'study',          x: 12, y: 17, width: 8,  height: 8,  floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 12, y: 25, width: 8,  height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 27, width: 8,  height: 10, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 8,  y: 33, width: 12, height: 7,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 13, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 13, y: 0,  width: 7,  height: 8,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 12, height: 12, floor: 2 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 12, y: 14, width: 8,  height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 13, y: 8,  width: 7,  height: 6,  floor: 2 },
      { name: 'Terrace',         type: 'courtyard',      x: 0,  y: 26, width: 20, height: 14, floor: 2 },
    ],
  },
  {
    id: 'template-ROWHOUSE-N-15x50-SouthIndian',
    bhkType: '2BHK', style: 'Traditional', facing: 'N',
    plotWidth: 15, plotHeight: 50, vastuScore: 73,
    tags: ['north-facing', 'row-house', 'south-indian', 'narrow', 'long-plot'],
    description: 'Long narrow South Indian row house 15×50ft. Traditional proportions, inner courtyard, rear utility.',
    rooms: [
      { name: 'Verandah',        type: 'foyer',          x: 0,  y: 0,  width: 15, height: 5,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 8,  y: 5,  width: 7,  height: 7,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 5,  width: 8,  height: 12, floor: 1 },
      { name: 'Inner Courtyard', type: 'courtyard',      x: 3,  y: 17, width: 9,  height: 8,  floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 0,  y: 25, width: 8,  height: 12, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 8,  y: 12, width: 7,  height: 14, floor: 1 },
      { name: 'Bathroom G',      type: 'bathroom',       x: 8,  y: 26, width: 7,  height: 8,  floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 0,  y: 37, width: 15, height: 8,  floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 0,  y: 45, width: 8,  height: 5,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 10, height: 14, floor: 2 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 10, y: 0,  width: 5,  height: 7,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 14, width: 10, height: 12, floor: 2 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 10, y: 7,  width: 5,  height: 7,  floor: 2 },
      { name: 'Open Terrace',    type: 'courtyard',      x: 0,  y: 26, width: 15, height: 24, floor: 2 },
    ],
  },

  // ── WESTERN STYLES ────────────────────────────────────────────────────────
  {
    id: 'template-CRAFTSMAN-N-50x70-Western',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 50, plotHeight: 70, vastuScore: 74,
    tags: ['north-facing', 'craftsman', 'western', 'bungalow', 'arts-crafts'],
    description: 'American Craftsman bungalow on 50×70ft. Covered front porch, built-in cabinets, cozy layout.',
    rooms: [
      { name: 'Front Porch',      type: 'foyer',          x: 12, y: 0,  width: 26, height: 8,  floor: 1 },
      { name: 'Entry Hall',       type: 'foyer',          x: 20, y: 8,  width: 10, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 8,  width: 28, height: 20, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 28, y: 8,  width: 22, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 28, y: 26, width: 22, height: 16, floor: 1 },
      { name: 'Breakfast Nook',   type: 'dining_room',    x: 0,  y: 28, width: 16, height: 10, floor: 1 },
      { name: 'Mudroom',          type: 'foyer',          x: 0,  y: 38, width: 12, height: 10, floor: 1 },
      { name: 'Powder Room',      type: 'bathroom',       x: 12, y: 38, width: 10, height: 8,  floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 22, y: 42, width: 28, height: 20, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 48, width: 20, height: 18, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 20, y: 48, width: 10, height: 12, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 66, width: 18, height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-FARMHOUSE-N-60x90-Western',
    bhkType: '4BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 60, plotHeight: 90, vastuScore: 75,
    tags: ['north-facing', 'farmhouse', 'western', 'country', 'wrap-porch', '4bhk'],
    description: 'Modern American farmhouse on 60×90ft. Wrap-around porch, barn doors, shiplap accents, family mud room.',
    rooms: [
      { name: 'Wrap Porch',       type: 'foyer',          x: 0,  y: 0,  width: 60, height: 10, floor: 1 },
      { name: 'Foyer',            type: 'foyer',          x: 22, y: 10, width: 16, height: 8,  floor: 1 },
      { name: 'Great Room',       type: 'living_room',    x: 0,  y: 10, width: 36, height: 24, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 36, y: 10, width: 24, height: 20, floor: 1 },
      { name: 'Farmhouse Kitchen',type: 'kitchen',        x: 36, y: 30, width: 24, height: 20, floor: 1 },
      { name: 'Mudroom',          type: 'foyer',          x: 0,  y: 34, width: 14, height: 12, floor: 1 },
      { name: 'Powder Room',      type: 'bathroom',       x: 14, y: 34, width: 10, height: 8,  floor: 1 },
      { name: 'Laundry',          type: 'utility',        x: 14, y: 42, width: 10, height: 8,  floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 0,  y: 46, width: 30, height: 22, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 68, width: 24, height: 22, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 24, y: 68, width: 12, height: 14, floor: 1 },
      { name: 'Master Closet',    type: 'storage',        x: 24, y: 82, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 30, y: 50, width: 18, height: 18, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 48, y: 50, width: 12, height: 18, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 36, y: 68, width: 18, height: 22, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 54, y: 68, width: 6,  height: 16, floor: 1 },
    ],
  },
  {
    id: 'template-CAPECOD-N-40x60-Western',
    bhkType: '3BHK', style: 'Traditional', facing: 'N',
    plotWidth: 40, plotHeight: 60, vastuScore: 71,
    tags: ['north-facing', 'cape-cod', 'western', 'classic', 'dormer'],
    description: 'Cape Cod style on 40×60ft. Symmetrical 1.5-story, dormers, cozy living rooms, efficient use of space.',
    rooms: [
      { name: 'Entry Porch',      type: 'foyer',          x: 14, y: 0,  width: 12, height: 6,  floor: 1 },
      { name: 'Living Room',      type: 'living_room',    x: 0,  y: 6,  width: 24, height: 18, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 24, y: 6,  width: 16, height: 16, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 24, y: 22, width: 16, height: 14, floor: 1 },
      { name: 'Sunroom',          type: 'living_room',    x: 0,  y: 24, width: 16, height: 12, floor: 1 },
      { name: 'Powder Room',      type: 'bathroom',       x: 16, y: 24, width: 8,  height: 8,  floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 36, width: 22, height: 16, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 32, y: 36, width: 8,  height: 8,  floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 0,  y: 52, width: 22, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 0,  width: 18, height: 16, floor: 2 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 18, y: 0,  width: 18, height: 16, floor: 2 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 0,  y: 16, width: 12, height: 10, floor: 2 },
      { name: 'Hall',             type: 'foyer',          x: 12, y: 16, width: 12, height: 8,  floor: 2 },
    ],
  },
  {
    id: 'template-PRAIRIE-N-70x80-Western',
    bhkType: '4BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 70, plotHeight: 80, vastuScore: 73,
    tags: ['north-facing', 'prairie', 'western', 'frank-lloyd-wright', 'horizontal'],
    description: 'Prairie-style 4BHK on 70×80ft. Horizontal emphasis, overhanging eaves, open interior, connection to nature.',
    rooms: [
      { name: 'Covered Entry',    type: 'foyer',          x: 28, y: 0,  width: 14, height: 8,  floor: 1 },
      { name: 'Great Room',       type: 'living_room',    x: 0,  y: 8,  width: 50, height: 26, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 50, y: 8,  width: 20, height: 20, floor: 1 },
      { name: 'Dining Room',      type: 'dining_room',    x: 50, y: 28, width: 20, height: 18, floor: 1 },
      { name: 'Library',          type: 'study',          x: 0,  y: 34, width: 20, height: 18, floor: 1 },
      { name: 'Guest Bedroom',    type: 'bedroom',        x: 20, y: 34, width: 18, height: 16, floor: 1 },
      { name: 'Guest Bathroom',   type: 'bathroom',       x: 38, y: 34, width: 12, height: 12, floor: 1 },
      { name: 'Terrace East',     type: 'courtyard',      x: 0,  y: 52, width: 50, height: 14, floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 50, y: 46, width: 20, height: 20, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 66, width: 26, height: 14, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 26, y: 66, width: 14, height: 10, floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 40, y: 66, width: 18, height: 14, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 58, y: 66, width: 12, height: 14, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 26, y: 76, width: 14, height: 4,  floor: 1 },
    ],
  },
  {
    id: 'template-MEDITERRANEAN-N-60x80-Western',
    bhkType: '4BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 76,
    tags: ['north-facing', 'mediterranean', 'western', 'villa', 'courtyard', 'arched'],
    description: 'Mediterranean-style 4BHK on 60×80ft. Central cortile, arched loggia, terracotta accents, pool at rear.',
    rooms: [
      { name: 'Loggia',           type: 'foyer',          x: 20, y: 0,  width: 20, height: 8,  floor: 1 },
      { name: 'Grand Living',     type: 'living_room',    x: 0,  y: 8,  width: 35, height: 22, floor: 1 },
      { name: 'Formal Dining',    type: 'dining_room',    x: 35, y: 8,  width: 25, height: 18, floor: 1 },
      { name: 'Kitchen',          type: 'kitchen',        x: 35, y: 26, width: 25, height: 18, floor: 1 },
      { name: 'Cortile',          type: 'courtyard',      x: 10, y: 30, width: 25, height: 16, floor: 1 },
      { name: 'Family Room',      type: 'living_room',    x: 0,  y: 30, width: 10, height: 14, floor: 1 },
      { name: 'Master Suite',     type: 'master_bedroom', x: 0,  y: 44, width: 22, height: 20, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 44, width: 13, height: 12, floor: 1 },
      { name: 'Dressing Room',    type: 'storage',        x: 22, y: 56, width: 13, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 35, y: 44, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 35, y: 60, width: 18, height: 16, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 0,  y: 64, width: 18, height: 16, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 53, y: 44, width: 7,  height: 14, floor: 1 },
      { name: 'Pool',             type: 'courtyard',      x: 18, y: 64, width: 17, height: 16, floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 53, y: 58, width: 7,  height: 18, floor: 1 },
    ],
  },
  {
    id: 'template-CONTEMPORARY-N-60x80-OpenPlan',
    bhkType: '4BHK', style: 'Modern', facing: 'N',
    plotWidth: 60, plotHeight: 80, vastuScore: 78,
    tags: ['north-facing', 'contemporary', 'open-plan', 'smart-home', 'modern', 'family'],
    description: 'Contemporary open-plan 4BHK on 60×80ft. Seamless indoor-outdoor, smart home wired, solar-ready design.',
    rooms: [
      { name: 'Smart Entry',      type: 'foyer',          x: 22, y: 0,  width: 16, height: 8,  floor: 1 },
      { name: 'Open Living',      type: 'living_room',    x: 0,  y: 8,  width: 40, height: 26, floor: 1 },
      { name: 'Open Dining',      type: 'dining_room',    x: 40, y: 8,  width: 20, height: 20, floor: 1 },
      { name: 'Island Kitchen',   type: 'kitchen',        x: 40, y: 28, width: 20, height: 20, floor: 1 },
      { name: 'Outdoor Terrace',  type: 'courtyard',      x: 0,  y: 34, width: 24, height: 16, floor: 1 },
      { name: 'Home Office',      type: 'study',          x: 24, y: 34, width: 16, height: 14, floor: 1 },
      { name: 'Utility',          type: 'utility',        x: 40, y: 48, width: 10, height: 12, floor: 1 },
      { name: 'Garage',           type: 'garage',         x: 50, y: 48, width: 10, height: 22, floor: 1 },
      { name: 'Master Bedroom',   type: 'master_bedroom', x: 0,  y: 50, width: 22, height: 20, floor: 1 },
      { name: 'Master Bathroom',  type: 'bathroom',       x: 22, y: 50, width: 12, height: 12, floor: 1 },
      { name: 'Master Wardrobe',  type: 'storage',        x: 22, y: 62, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',        type: 'bedroom',        x: 0,  y: 70, width: 18, height: 10, floor: 1 },
      { name: 'Bedroom 3',        type: 'bedroom',        x: 18, y: 70, width: 18, height: 10, floor: 1 },
      { name: 'Bedroom 4',        type: 'bedroom',        x: 34, y: 60, width: 16, height: 10, floor: 1 },
      { name: 'Bathroom 2',       type: 'bathroom',       x: 34, y: 70, width: 16, height: 10, floor: 1 },
    ],
  },

  // ── SPECIAL TYPES ────────────────────────────────────────────────────────
  {
    id: 'template-JAPANESE-N-30x40-Zen',
    bhkType: '2BHK', style: 'Minimalist', facing: 'N',
    plotWidth: 30, plotHeight: 40, vastuScore: 72,
    tags: ['north-facing', 'japanese', 'zen', 'minimalist', 'garden', 'tatami'],
    description: 'Japanese Zen house on 30×40ft. Engawa corridor, zen garden courtyard, tatami room, sliding shoji partitions.',
    rooms: [
      { name: 'Genkan (Entry)',   type: 'foyer',          x: 11, y: 0,  width: 8,  height: 5,  floor: 1 },
      { name: 'Engawa',          type: 'foyer',          x: 0,  y: 5,  width: 30, height: 4,  floor: 1 },
      { name: 'Washitsu (Tatami)',type: 'living_room',    x: 0,  y: 9,  width: 16, height: 14, floor: 1 },
      { name: 'Zen Garden',      type: 'courtyard',      x: 16, y: 9,  width: 14, height: 14, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 0,  y: 23, width: 14, height: 10, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 14, y: 23, width: 16, height: 10, floor: 1 },
      { name: 'Bathroom',        type: 'bathroom',       x: 22, y: 33, width: 8,  height: 7,  floor: 1 },
      { name: 'Ofuro (Bath)',    type: 'bathroom',       x: 0,  y: 33, width: 8,  height: 7,  floor: 1 },
      { name: 'Bedroom 1',       type: 'bedroom',        x: 8,  y: 33, width: 14, height: 7,  floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 0,  width: 16, height: 5,  floor: 2 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 16, y: 0,  width: 14, height: 5,  floor: 2 },
    ],
  },
  {
    id: 'template-JOINTFAMILY-N-50x80-Traditional',
    bhkType: 'VILLA', style: 'Traditional', facing: 'N',
    plotWidth: 50, plotHeight: 80, vastuScore: 79,
    tags: ['north-facing', 'joint-family', 'traditional', 'india', 'multi-generation'],
    description: 'Joint family home on 50×80ft for 3 generations. Grandparents suite at ground, young family on first, shared spaces.',
    rooms: [
      // Ground floor - grandparents + common
      { name: 'Grand Verandah',  type: 'foyer',          x: 0,  y: 0,  width: 50, height: 6,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 38, y: 6,  width: 12, height: 12, floor: 1 },
      { name: 'Common Living',   type: 'living_room',    x: 0,  y: 6,  width: 38, height: 18, floor: 1 },
      { name: 'Inner Courtyard', type: 'courtyard',      x: 14, y: 24, width: 22, height: 16, floor: 1 },
      { name: 'Common Dining',   type: 'dining_room',    x: 0,  y: 24, width: 14, height: 18, floor: 1 },
      { name: 'Common Kitchen',  type: 'kitchen',        x: 36, y: 24, width: 14, height: 18, floor: 1 },
      { name: 'Grand Suite',     type: 'master_bedroom', x: 0,  y: 42, width: 18, height: 16, floor: 1 },
      { name: 'Grand Bathroom',  type: 'bathroom',       x: 18, y: 42, width: 10, height: 10, floor: 1 },
      { name: 'Grand Sitting',   type: 'living_room',    x: 28, y: 42, width: 16, height: 10, floor: 1 },
      { name: 'Guest Room',      type: 'bedroom',        x: 0,  y: 58, width: 16, height: 14, floor: 1 },
      { name: 'Guest Bathroom',  type: 'bathroom',       x: 16, y: 58, width: 10, height: 10, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 26, y: 52, width: 14, height: 10, floor: 1 },
      { name: 'Staircase',       type: 'staircase',      x: 40, y: 52, width: 10, height: 12, floor: 1 },
      // First floor - young family
      { name: 'F.F. Master',     type: 'master_bedroom', x: 0,  y: 0,  width: 20, height: 22, floor: 2 },
      { name: 'F.F. Master Bath',type: 'bathroom',       x: 20, y: 0,  width: 10, height: 12, floor: 2 },
      { name: 'F.F. Kids Room 1',type: 'bedroom',        x: 30, y: 0,  width: 20, height: 20, floor: 2 },
      { name: 'F.F. Kids Room 2',type: 'bedroom',        x: 0,  y: 22, width: 18, height: 18, floor: 2 },
      { name: 'F.F. Bathroom',   type: 'bathroom',       x: 18, y: 22, width: 12, height: 10, floor: 2 },
      { name: 'F.F. Study',      type: 'study',          x: 30, y: 20, width: 20, height: 16, floor: 2 },
      { name: 'Open Terrace',    type: 'courtyard',      x: 0,  y: 40, width: 50, height: 20, floor: 2 },
    ],
  },
  {
    id: 'template-ECOGREEN-N-40x60-Sustainable',
    bhkType: '3BHK', style: 'Contemporary', facing: 'N',
    plotWidth: 40, plotHeight: 60, vastuScore: 79,
    tags: ['north-facing', 'eco-green', 'sustainable', 'solar', 'rain-harvest', 'passive-cooling'],
    description: 'Eco-sustainable 3BHK on 40×60ft. Passive cooling courtyard, solar roof, rain harvesting, kitchen garden.',
    rooms: [
      { name: 'Eco Foyer',       type: 'foyer',          x: 14, y: 0,  width: 12, height: 6,  floor: 1 },
      { name: 'Pooja Room',      type: 'pooja_room',     x: 28, y: 0,  width: 12, height: 8,  floor: 1 },
      { name: 'Living Room',     type: 'living_room',    x: 0,  y: 6,  width: 26, height: 18, floor: 1 },
      { name: 'Passive Courtyard', type: 'courtyard',    x: 26, y: 8,  width: 14, height: 16, floor: 1 },
      { name: 'Kitchen Garden',  type: 'courtyard',      x: 0,  y: 24, width: 14, height: 12, floor: 1 },
      { name: 'Dining Room',     type: 'dining_room',    x: 14, y: 24, width: 12, height: 12, floor: 1 },
      { name: 'Kitchen',         type: 'kitchen',        x: 26, y: 24, width: 14, height: 14, floor: 1 },
      { name: 'Utility',         type: 'utility',        x: 0,  y: 36, width: 10, height: 10, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 46, width: 18, height: 14, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 18, y: 46, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 0,  y: 38, width: 18, height: 8,  floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 28, y: 38, width: 12, height: 14, floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 18, y: 38, width: 10, height: 6,  floor: 1 },
      { name: 'Rain Harvest',    type: 'utility',        x: 10, y: 36, width: 10, height: 8,  floor: 1 },
    ],
  },
  {
    id: 'template-PENTHOUSE-N-60x60-Modern',
    bhkType: '4BHK', style: 'Modern', facing: 'N',
    plotWidth: 60, plotHeight: 60, vastuScore: 80,
    tags: ['north-facing', 'penthouse', 'luxury', 'modern', 'sky-villa', '4bhk'],
    description: 'Penthouse-style single-floor villa on 60×60ft. Sky lounge, wraparound terrace, jacuzzi deck, home cinema.',
    rooms: [
      { name: 'Private Lift',    type: 'foyer',          x: 24, y: 0,  width: 12, height: 8,  floor: 1 },
      { name: 'Sky Lounge',      type: 'living_room',    x: 0,  y: 8,  width: 36, height: 24, floor: 1 },
      { name: 'Dining',          type: 'dining_room',    x: 36, y: 8,  width: 24, height: 18, floor: 1 },
      { name: 'Chef Kitchen',    type: 'kitchen',        x: 36, y: 26, width: 24, height: 18, floor: 1 },
      { name: 'Cinema Room',     type: 'living_room',    x: 0,  y: 32, width: 22, height: 18, floor: 1 },
      { name: 'Jacuzzi Deck',    type: 'courtyard',      x: 22, y: 32, width: 14, height: 18, floor: 1 },
      { name: 'Master Bedroom',  type: 'master_bedroom', x: 0,  y: 50, width: 22, height: 10, floor: 1 },
      { name: 'Master Bathroom', type: 'bathroom',       x: 22, y: 50, width: 12, height: 8,  floor: 1 },
      { name: 'Bedroom 2',       type: 'bedroom',        x: 34, y: 50, width: 16, height: 10, floor: 1 },
      { name: 'Bedroom 3',       type: 'bedroom',        x: 50, y: 44, width: 10, height: 10, floor: 1 },
      { name: 'Bedroom 4',       type: 'bedroom',        x: 50, y: 54, width: 10, height: 6,  floor: 1 },
      { name: 'Bathroom 2',      type: 'bathroom',       x: 22, y: 58, width: 12, height: 2,  floor: 1 },
      { name: 'Wraparound Terrace', type: 'courtyard',   x: 0,  y: 0,  width: 24, height: 8,  floor: 1 },
    ],
  },
]

async function main() {
  console.log(`Seeding batch 5: ${batch5.length} templates…`)
  for (const t of batch5) {
    await db.planTemplate.upsert({
      where: { id: t.id },
      update: { vastuScore: t.vastuScore, rooms: t.rooms, tags: t.tags, description: t.description },
      create: { ...t, plotUnit: 'ft', isPublic: true, useCount: 0 },
    })
    console.log(`  ✓ ${t.id}`)
  }
  console.log(`\nBatch 5 complete: ${batch5.length} templates`)
}

main().catch(console.error).finally(() => db.$disconnect())
